### ISSUE TITLE
Issue with adding second Maker

### ISSUE THREAD

**Issue by rkokfhung** [rudders/homebridge-platform-wemo#103]
Hi all,
I am wondering if someone can assist me. I just started using a Wemo Maker and managed to get homebridge working perfectly with it. I have hooked it up as a Gate opener without issues.

Today I went and bought myself a second Maker, and planned to have it to control the Garage. The problem is when I rerun homebridge it detects both makers (old=Wemo Maker Gate, new=Garage), it now crashes. Everytime I turn off the second maker, homebridge will start okay. What is the issue here?

**homebridge output:**

> [6/13/2017, 6:16:20 PM] [WeMo Platform] Online: Garage [94103ED3E4D0]
> [6/13/2017, 6:16:20 PM] [WeMo Platform] Online: WeMo Maker Gate [94103ED3F954]
> [6/13/2017, 6:16:20 PM] [WeMo Platform] WeMo Maker Gate - Get Current Door State: Closed
> [6/13/2017, 6:16:20 PM] [WeMo Platform] Garage - Get Current Door State: Open
> events.js:160
>       throw er; // Unhandled 'error' event
>       ^
> 
> TypeError: Cannot read property 'forEach' of undefined
>     at /usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:365:41
>     at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:489:18)
>     at emitOne (events.js:96:13)
>     at Parser.emit (events.js:188:7)
>     at Object.onclosetag (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:447:26)
>     at emit (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:640:35)
>     at emitNode (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:645:5)
>     at closeTag (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:905:7)
>     at Object.write (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:1452:13)
>     at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:508:31)
>     at Parser.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:7:59)
>     at Object.exports.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:540:19)
>     at Object.attributeList (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:361:14)
>     at /usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:382:22
>     at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:489:18)
>     at emitOne (events.js:96:13)
> 

My config.json:

{
        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "port": 51826,
                "pin": "xxxxxxxx"
        },

        "platforms": [{
                        "platform": "Camera-ffmpeg",
                        "cameras": [{
                        ]
                },
                {
                        "platform": "BelkinWeMo",
                        "name": "WeMo Platform"
                }
        ]
}

**Comment by rkokfhung** [comment]
Solved! Needed to update second maker's firmware to
WeMo_WW_2.00.10926.PVT-OWRT-Maker

The older firmware was producing status under attributelist instead of paramlist

**Comment by devbobo** [comment]
@rkokfhung thanks for the followup, I'll see if I can get a fix added to `wemo-client` to prevent that issue in the future.

**Comment by rkokfhung** [comment]
Thanks David. I had the debug log at home that shows the difference if that
would help. I was just updating the issue on the train just now so trying
to recall at best I can.

**Comment by devbobo** [comment]
@rkokfhung if you have the detail, it would be useful...thanks

**Comment by rkokfhung** [comment]
@devbobo Here it is. What I noticed was the older firmware was providing status using <attributelist>, while latest firmware its under <ParamString>. I'm guessing here is the problem?

**Good Wemo Maker with firmware - "firmwareVersion":"WeMo_WW_2.00.10926.PVT-OWRT-Maker"**

6/13/2017, 10:08:18 PM] [WeMo Platform] WeMo Maker Gate - Get Current Door State: Closed
  wemo-client Incoming Request for uuid:Maker-1_0-221603S000005E:sensor:switch: <e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
**<ParamString>1</ParamString>**
</e:property>
</e:propertyset>

 +14ms
  wemo-client Unhandled Event: ParamString +3ms
  wemo-client GetAttributes Response:  { 's:Envelope': 
   { '$': 
      { 'xmlns:s': 'http://schemas.xmlsoap.org/soap/envelope/',
        's:encodingStyle': 'http://schemas.xmlsoap.org/soap/encoding/' },
     's:Body': { 'u:GetAttributesResponse': [Object] } } } +5ms

**Bad Wemo Maker with older firmware -"firmwareVersion":"WeMo_WW_2.00.6529.PVT"**
[6/13/2017, 10:08:18 PM] [WeMo Platform] Garage - Get Current Door State: Open
  wemo-client Incoming Request for uuid:Maker-1_0-221549S00002A7:sensor:switch: <e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
**<attributeList>1</attributeList>**
</e:property>
</e:propertyset>

 +20ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'forEach' of undefined
    at /usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:365:41
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Object.onclosetag (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:645:5)
    at closeTag (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:905:7)
    at Object.write (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:1452:13)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:508:31)
    at Parser.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:7:59)
    at Object.exports.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:540:19)
    at Object.attributeList (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:361:14)
    at /usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:382:22
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:96:13)
