### ISSUE TITLE
Can custom Characteristic or Service work in iPhone Homekit??

### ISSUE THREAD

**Issue by rench** [rudders/homebridge-platform-wemo#104]
Hello ebaauw, I see your project using a custom Characteristic or Service, and I also try to customize some Characteristic such as the display unit for kWh. But these are not shown in the iphone's Homkit software. Can these custom attributes be used in Homekit? How do I need to work?

**Comment by devbobo** [comment]
@rench are you talking about the official `Home` app ? If so, that app only shows officially supported `Characteristics` or `Services`.

**Comment by rench** [comment]
Ok, I see. IPhone comes with the family App does not support. Thank you
