### ISSUE TITLE
Wemo Insight Switch

### ISSUE THREAD

**Issue by hassancy** [rudders/homebridge-platform-wemo#106]
I am trying to get information other than on/off from my Wemo Insight Switch in HomeKit. Specifically I was to know if the insight switch is on Standby (i.e. the connected device is not drawing power below a certain level) and/or how much current is the attached device drawing.  I know that this data is available in https://github.com/timonreinhard/wemo-client.  The section below from the README says indicates the setup.  Can these parameters be included in the homebridge memo platform?

Event: insightParams (binaryState, instantPower, data)

Wemo Insight Switch sent new power consumption data.

String binaryState 1 = on, 0 = off, 8 = standby
String instantPower Current power consumption in mW
Object data Aggregated usage data

**Comment by devbobo** [comment]
@hassancy what app are you using ? The official `Home` app from Apple is only relatively new and doesn't support everything that is supported by `HomeKit`. To view this additional information you will need to use an app like `Eve` from Elgato.

![img_0394](https://user-images.githubusercontent.com/680871/27811874-0504abda-60ae-11e7-992d-84f89edafbbe.PNG)
