### ISSUE TITLE
discover stopped working

### ISSUE THREAD

**Issue by geofbuck** [rudders/homebridge-platform-wemo#107]
I can confirm that the platform loads but does not discover my 4 memo devices. Killing home bridge and deleting caches, then re-adding bridge will see the devices, but attempting to add them to a room pops up a message that the accessory cannot be communicated with and is not on the network. They show up in the Wemo app correctly and can be cycled on/off. It does not update the status in home kit. Wemo did a recent update I suspect has broken the discovery method, but the platform still seems to load ok, just doesn't do anything.

**Comment by starlessblack** [comment]
I believe I, too, just started experiencing this problem. I don't know what happened because my Wemo plugs have not gotten a new firmware in quite some time. I've just noticed at some point in the last couple days the Wemo plugs don't seem to respond in Homekit apps, only from the Wemo app itself. After restarting Homebridge, I see in the log where it loads the Wemo platform plugin, but it doesn't discover any devices as far as I can tell--I believe I used to see in the logs where it would the plugin would discovery devices and then of course change their status in the log when turned on/off.

**Comment by geofbuck** [comment]
I removed the platform-wemo plugin and tried the homebridge wemo one that just adds your devices as accessories. It works but has issues as well. Every couple of days i have to power cycle them to get them to show up properly in homekit. Pain in the butt!

**Comment by geofbuck** [comment]
I tried following some of the suggestions from the other closed issue about discovery problems to no avail. My 4 devices just aren't being discovered. I can see the platform load but it never tries to discover on homebridge start. I tried re-install, deleting caches, etc. Here is my output:

homebridge
[7/27/2017, 4:52:02 PM] Loaded plugin: homebridge-globalcache-itach
[7/27/2017, 4:52:02 PM] Registering platform 'homebridge-globalcache-itach.GlobalCacheItach'
[7/27/2017, 4:52:02 PM] ---
[7/27/2017, 4:52:02 PM] Loaded plugin: homebridge-indigo
[7/27/2017, 4:52:02 PM] Registering platform 'homebridge-indigo.Indigo'
[7/27/2017, 4:52:02 PM] ---
[7/27/2017, 4:52:02 PM] Loaded plugin: homebridge-kevo
[7/27/2017, 4:52:02 PM] Registering accessory 'homebridge-kevo.Kevo'
[7/27/2017, 4:52:02 PM] ---
[7/27/2017, 4:52:03 PM] Loaded plugin: homebridge-nest
[7/27/2017, 4:52:03 PM] Registering platform 'homebridge-nest.Nest'
[7/27/2017, 4:52:03 PM] ---
[7/27/2017, 4:52:03 PM] Loaded plugin: homebridge-platform-myq
[7/27/2017, 4:52:03 PM] Registering platform 'homebridge-platform-myq.MyQ'
[7/27/2017, 4:52:03 PM] ---
[7/27/2017, 4:52:03 PM] Loaded plugin: homebridge-platform-ring-video-doorbell
[7/27/2017, 4:52:03 PM] Registering platform 'homebridge-platform-ring-video-doorbell.ring-video-doorbell'
[7/27/2017, 4:52:03 PM] ---
[7/27/2017, 4:52:03 PM] Loaded plugin: homebridge-platform-wemo
[7/27/2017, 4:52:03 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[7/27/2017, 4:52:03 PM] ---
[7/27/2017, 4:52:03 PM] Loaded config.json with 1 accessories and 6 platforms.
[7/27/2017, 4:52:03 PM] ---
[7/27/2017, 4:52:03 PM] Loading 6 platforms...
[7/27/2017, 4:52:03 PM] [MyQ Platform] Initializing MyQ platform...
[7/27/2017, 4:52:03 PM] [WeMo Platform] Initializing BelkinWeMo platform...
[7/27/2017, 4:52:03 PM] [Doorbell] Initializing ring-video-doorbell platform...
[7/27/2017, 4:52:03 PM] Initializing Nest platform...
[7/27/2017, 4:52:03 PM] Fetching Nest devices.
[7/27/2017, 4:52:03 PM] [My Home] Initializing Indigo platform...
[7/27/2017, 4:52:03 PM] [My Home] Indigo base URL is http://127.0.0.1:8176
[7/27/2017, 4:52:03 PM] [Global Cache Itach] Initializing GlobalCacheItach platform...
[7/27/2017, 4:52:03 PM] Loading 1 accessories...
[7/27/2017, 4:52:03 PM] [Back Door] Initializing Kevo accessory...
[7/27/2017, 4:52:03 PM] [Doorbell] didFinishLaunching
[7/27/2017, 4:52:03 PM] [My Home] Listening on port 8178

And here is part of my config:

                  {
                  "platform": "BelkinWeMo",
                  "name": "WeMo Platform",
                  "expected_accessories": "4",
                  "timeout": "25",
                  "discovery": "true",
                  "noMotionTimer": "30",
                  "homekit_safe": "1"
                  },

**Comment by geofbuck** [comment]
Alright, I resorted to DHCP IP reservation for the 4 devices, turned discovery off, then manually added the addresses to the homebridge config file and problem solved. They showed up in homebridge right away! Cheers to the other posts for providing the info.

**Comment by starlessblack** [comment]
I’ve always used DHCP reservation so I guess my problem is caused by something else. I did make some adjustments to my networks access points, so I’ll see if that has any discernible effect.

**Comment by geofbuck** [comment]
Do they show up in terminal at all when homebridge starts? Or just the "registering platform" line? Did you delete the /.homebridge/accessories/cachedAccessories file? That could be causing problems as well.

**Comment by starlessblack** [comment]
No, when the problem is occurring, when Homebridge starts, I see the WeMo platform plugin load along with all the others, but the wemo devices aren’t detected and loaded. It’s only after I power cycle them that homebridge plugin seems to be able to detect them. perhaps I’ll trying clearing the cached accessories again.

**Comment by geofbuck** [comment]
Did you turn off discovery and add them manually? Do that then clear accesory cache.

**Comment by starlessblack** [comment]
Oh jeez, I forgot all about that in the documentation. It'd been working well for a while with auto discovery so I guess that didn't even occur to me. So what'd you do, set discovery to false and the in the manual devices section, add all my device addresses in the format http://192.168.x.x:49153/setup.xml?

**Comment by geofbuck** [comment]
Correct! That's why I used DHCP reservation. Trust me it will work properly!

**Comment by starlessblack** [comment]
And I guess I don't know how to properly notate an array of devices in the config.json in that "manualDevices" field. Separating by commas or spaces didn't seem to work, causing startup failure.

**Comment by geofbuck** [comment]
I'll post the relevant bits in a bit. Just lost all power in my neighborhood. Argh!

**Comment by starlessblack** [comment]
Well, I got the config.json at least correct to the point that it doesn't error out, but maybe I still have the syntax for that "manualDevices" property wrong because it seems to be ignoring it. I've tested the IPs and their setup.xml URLs, and they're all correct and load in my browser. Stumped :(

**Comment by devbobo** [comment]
@starlessblack the `manualDevices` in the config.json should look something like this...

```
   "platforms": [
       {
           "platform": "BelkinWeMo",
           "name": "WeMo Platform",
           "manualDevices": [
               "http://192.168.1.20:49153/setup.xml",
               "http://192.168.1.21:49153/setup.xml",
               "http://192.168.1.22:49153/setup.xml"
               
           ]
       }
   ]
```

You will need to confirm that each manual device url loads correctly via a web browser.

**Comment by dazza120** [comment]
Sorry to butt in here I would be interested in how you do the static ip's for wemo, all the wemo devices I have, have had their ip's reserved via the router but things I don't understand is how do I add the ip's to config.json file? But from the looks of it, it doesn't look like just adding IP address? Can I get some help please.

**Comment by devbobo** [comment]
@dazza120 if you have static ips for your wemo devices, copying one of the urls from above anf replace the static ip section (shown below) with one of your known static ips and see if it loads successfully in a browser.

![discover_stopped_working_ _issue__107_ _rudders_homebridge-platform-wemo](https://user-images.githubusercontent.com/680871/28763624-c65a745e-7602-11e7-9822-e256a618823a.png)

**Comment by dazza120** [comment]
@devbobo thank you very much I'll do that later much appreciated cheers

**Comment by starlessblack** [comment]
Thank you very much @devbobo I was completely neglecting to put in the [] brackets in my array. Works perfectly now!

**Comment by dazza120** [comment]
@devbobo perfect pic's them up a treat. Thank you

**Comment by geofbuck** [comment]
thanks for stepping in @devbobo I was too busy to respond quickly. Glad you guys sorted it out!
