### ISSUE TITLE
Wemo Dimmer

### ISSUE THREAD

**Issue by aguilucho2017** [rudders/homebridge-platform-wemo#110]
Hi !

Is it possible to add the Wemo Dimmer to the plugin?.
The Wemo-client latest version added support to it.

Would be great!

https://github.com/timonreinhard/wemo-client

Maybe that code can be used for the plugin, at least for basic 
support to switch on/off the dimmer.

Thanks
Martin.

**Comment by aguilucho2017** [comment]
Of What I can see in:
https://github.com/timonreinhard/wemo-client/pull/54/commits/8a08e61a81e7b302595ddbf769d729b8928d711a

The URN to use it as a simple switch is:
+  Dimmer: 'urn:Belkin:device:dimmer:1',

**Comment by devbobo** [comment]
Hi @aguilucho2017,

yes, that PR has been merged into wemo-client but Timon hasn't released a new version (eg. 0.1.4) with those changes.

More than happy to add the changes once Timon releases a new version...
![commits_ _timonreinhard_wemo-client_](https://user-images.githubusercontent.com/680871/29051182-1c56a34c-7c24-11e7-951a-4a2b0a6a12de.png)

**Comment by aguilucho2017** [comment]
Hi David

What I can see is that for simple support, without dimming is just  taking as valid the dimmer urn right?. If it's not that easy then we will have to wait. 

Thanks much!!
Martin

**Comment by devbobo** [comment]
@aguilucho2017 there is an existing PR where @markhatchell has implemented the changes, once Timon releases that version, I can merge that PR.

https://github.com/rudders/homebridge-platform-wemo/pull/105

**Comment by aguilucho2017** [comment]
Hi David

Wemo client v1.0.4 is out  can you release the new version of wemo platform with wemo dimmer support now? Thanks!

**Comment by aguilucho2017** [comment]
Hello?

**Comment by ayanm00** [comment]
Hi,
I am also waiting for this update to buy a WeMo Dimmer. Just a note for anyone interested: Best Buy is offering 2 WeMo Dimmers for $110 if you create a free MyBestBuy account. 

Thanks for you work! This is my most used plugin!

**Comment by lucanaut** [comment]
Same here! I love this plugin!  Thank you for all the hard work.  I have installed a few dimmers and really like them.  Can't wait to add them to my homebridge!

**Comment by devbobo** [comment]
Sorry for the delay with this, I've had a lot going on. The new version `1.3.2` supports the `WeMo Dimmer`, but you will need to upgrade to `Node 6` or higher if you aren't already.

**Comment by lucanaut** [comment]
Thank you!  I updated and it's working!!

**Comment by ayanm00** [comment]
Any idea if/when dimming will be supported? Best Buy is offering the dinners for $50 during Black Friday. Thanks for all your hard work! We really appreciate it!

**Comment by KaidenR** [comment]
I've submitted a PR that updates the Dimmer switches with brightness controls! https://github.com/rudders/homebridge-platform-wemo/pull/122

But, like the PR mentions, I'm waiting for another PR to merge first. Hopefully that happens soon!

**Comment by KaidenR** [comment]
@devbobo This issue can probably be closed now that the dimmer functionality is merged.

**Comment by devbobo** [comment]
added in the latest version

**Comment by hakt0-r** [comment]
It seems that the changes pertaining to this have been reversed? Am I right as I still cannot control the brightness through the Dimmer.
