### ISSUE TITLE
Motion Sensor

### ISSUE THREAD

**Issue by NDNELSON** [rudders/homebridge-platform-wemo#114]
Hi and Thaks for developing this pluging. I have a question about how does motion sensor works with homebridge.

My main question is if motion sensor sends information when detects triggering motion to homebridge plugin or if homebridge plugin is scanning sensor´s activity periodically.

It is coz i want to develop my own motion sensors, and it seems that wemo works with upnp and soap.

Thank you for your atention. Best Regards

**Comment by devbobo** [comment]
@NDNELSON the sensor is not polled, the WeMo motion sensor sends an event message when motion is sensed or not longer sensed.
