### ISSUE TITLE
Question: Wemo Light Switch Functionality

### ISSUE THREAD

**Issue by 350d** [rudders/homebridge-platform-wemo#115]
Hello! Just a question before i can order my Wemo Light Switch. What exact options available for this device? Can i use single click and long click functions for example?
I would like to short power line inside the socket and use this switch as remote controller for other devices via Homebridge. Is this possible?

**Comment by DMBlakeley** [comment]
The Wemo functionality of “long press” is not available in HomeKit via Homebridge.  Only on/off is supported.  You can create an automation in HomeKit that one accessory can trigger other actions, for example, turning on the front porch light would also turn on the living room lights.  

Not sure about your idea of shorting the power line inside of the socket.  I would think it would be better to use a relay to provide the interface and electrical isolation between the switch and the device you want to control.  You could also consider using the Wemo Maker but Homebridge assumes that if you are using the Maker it is for a garage door.

**Comment by devbobo** [comment]
Personally, I'd look at something like [Flic buttons](http://flic.io)....that seems more like what you are trying to achieve. There is a homebridge plugin for them...but you need to setup some way to communicate without over bluetooth. More info at https://www.npmjs.com/package/homebridge-flic
