### ISSUE TITLE
Wemo insight energy usage timestamp 

### ISSUE THREAD

**Issue by dvd2000k** [rudders/homebridge-platform-wemo#116]
Hi, is there a way to disable wemo insight energy usage timestamp in the homebridge log? I have the log full of energy usage by the wemo insight every second.

**Comment by DMBlakeley** [comment]
You can edit the index.js in the "homebridge-platform-wemo" directory using an appropriate source code editor (for example Atom or TextWrangler) to disable logging.

To disable real-time energy logging, comment out line 654 (by placing // at the beginning of the line), 
//      this.log("%s - Consumption: %sw", this.accessory.displayName, value);

To disable overall power logging, comment out line 839,
//     this.log("%s - Total Consumption: %skwh", this.accessory.displayName, value);

You will then need to restart homebridge for the changes to take effect.

**Comment by dvd2000k** [comment]
Perfect, It Work! Thank you very much!
