### ISSUE TITLE
plug-in seems to require unreleased version of Homebridge

### ISSUE THREAD

**Issue by VdkaShaker** [rudders/homebridge-platform-wemo#118]
I'm getting:

> Error: Plugin /usr/lib/node_modules/homebridge-platform-wemo requires a HomeBridge version of >=0.4.29 which does not satisfy the current HomeBridge version of 0.4.28. You may need to upgrade your installation of HomeBridge.

https://github.com/nfarina/homebridge/releases

Only lists 4.28 as most recent.

**Comment by devbobo** [comment]
I'd ignore the releases tab, it doesn't really mean anything, this is where you should look for current versions...
https://www.npmjs.com/package/homebridge

**Comment by VdkaShaker** [comment]
I'm confused by you closing this.  I cannot use this plug-in because it fails to load with the error I posted above.  Will it be fixed so it will load?

**Comment by devbobo** [comment]
There is nothing to fix, upgrade `homebridge` as the error message is telling you.

`sudo npm install -g --unsafe-perm homebridge`

**Comment by VdkaShaker** [comment]
Ah.  well I cannot upgrade directly as I'm using it as an add-on which someone else controls.  Is there a reason you are requiring the most recent version?  Could you relax that requirement without causing issues for those of us who haven't (or cannot) updated Homebridge just yet?

**Comment by devbobo** [comment]
The latest version `wemo-client` requires `node` version `6` or higher. Prior to `homebridge` version `0.4.29`, errors relating to incorrect node version weren't displayed correctly. This is an attempt to prevent support requests as to why stuff is no longer working.

You can edit the `package.json` file to match the version of homebridge you are running, and it will work fine.

**Comment by VdkaShaker** [comment]
Understood.  I'm notifying the owner of the add-on I'm using as well to see if he can upgrade, but he was under the impression 4.28 was latest released.  Thanks for the info.

**Comment by devbobo** [comment]
While the `releases` tab is a good indication of the current release, it requires the developer to `tag` the release and push those `tags` to github....however, that can be easily overlooked.

The best source of truth is looking at the npmjs page as that is what has been deployed.

**Comment by VdkaShaker** [comment]
Got it.  Developer of the Home-Assistant/Hass.io Homebridge add-on which I'm using is reticent to push unreleased versions of Homebridge (understandably).  I'm sharing this info with him.

**Comment by DMBlakeley** [comment]
I upgraded homebridge today.  The current released version is 0.4.29.  I updated homebridge first and then upgraded homebridge-platform-wemo.  All went smoothly.

**Comment by VdkaShaker** [comment]
Thanks!  Appreciate everyone’s work on all these pieces.
