### ISSUE TITLE
Wemo maker garage opener receives set state twice

### ISSUE THREAD

**Issue by rkokfhung** [rudders/homebridge-platform-wemo#119]
Hi all
I’m not sure if anyone has encountered this. Nothing has changed in my setup and I’ve had My homebridge and the wemo platform working for close to six months without issues. Recently my gate and garage would open or close but then stops half way. 

Looking at the homebridge printouts it looks like HomeKit receives a second set command about ten seconds later:

11/1/2017, 7:56:19 AM] [WeMo Platform] Garage - Set Target Door State: Open (triggered by HomeKit)
[11/1/2017, 7:56:19 AM] [WeMo Platform] Gate - Set Target Door State: Open (triggered by HomeKit)
[11/1/2017, 7:56:22 AM] [WeMo Platform] Garage - Get Current Door State: Opening
[11/1/2017, 7:56:22 AM] [WeMo Platform] Gate - Get Current Door State: Opening
>>>> 13secs later <<<<<<
[11/1/2017, 7:56:32 AM] [WeMo Platform] Gate - Set Target Door State: Open (triggered by HomeKit)
[11/1/2017, 7:56:32 AM] [WeMo Platform] Gate - Get Current Door State: Stopped
[11/1/2017, 7:56:32 AM] [WeMo Platform] Garage - Set Target Door State: Open (triggered by HomeKit)
[11/1/2017, 7:56:32 AM] [WeMo Platform] Garage - Get Current Door State: Stopped

I believe this is only happening when I’m using Siri on the watch. If I press the buttons in Home on the iPhone, or use Siri directly on the phone, it doesn’t do that. I don’t think it’s the recent WatchOS update either as I recall everything was working fine after I did my ios11/watchOS upgrades recently. 

I was wondering if I could modify the codes to check the last current state, so that if it is opening or closing for the last X seconds it would ignore the second set command?

Anyone else having this issue?

I’m on ios11.0.3
WatchOS 4.0

Thanks
Richard

**Comment by DMBlakeley** [comment]
iOS 11.1, tvOS 11.1 and WatchOS 4.1 were released today.  I would first update your devices to these releases to see if you still have the issue.  I was running tvOS 11.1 beta on my Apple TV and found that it worked more consistently than tvOS 11.

**Comment by rkokfhung** [comment]
Thanks @DMBlakeley . I'll try that tonight! I'll give it a go too and see if there's a difference if i'm on Wifi or on Cellular (via AppleTV).

**Comment by rkokfhung** [comment]
Hey @DMBlakeley, updated everything. Still does it. I can confirm it’s  only happening if via Siri on the Watch. From phone, whether it’s wifi or cellular it doesn’t do it. What’s the best thing to do? Modify index.js to ignore the second SET command?

**Comment by rkokfhung** [comment]
Fixed! Added checks for closing /opening states. Woohoo

**Comment by rkokfhung** [comment]
Fixed! Added checks for closing /opening states. Woohoo

**Comment by rkokfhung** [comment]
Thanks @devbobo ! I should have done an update first too on the plugin. But I'm also glad I figured out how to make it work again :) Will update it when I get home!

**Comment by rkokfhung** [comment]
@devbobo Just checked the changes you uploaded ....its exactly what I did! :) haha!
