### ISSUE TITLE
device discovery

### ISSUE THREAD

**Issue by dwery** [rudders/homebridge-platform-wemo#12]
The plugin very rarely discovers all of my WeMo devices. I'd suggest to send out multiple discovery packets as I'm guessing that the discovery process is somewhat not being able to receive all the replies. I've checked with tcpdump and the devices are actually responding to the discovery.

**Comment by rudders** [comment]
It is very annoying and the discover is in a couple of downstream modules. I'm sufficiently frustrated with the process that it's tempting to revert to the accessory model. Interesting about your tcpdump analysis - might be worth persisting but I find the Wemo app also struggles with discovery quite frequently and I have simplified my home network substantially to try and increase reliability.

**Comment by dwery** [comment]
While analyzing, I also noticed that sometimes the WeMo devices are not responding. I've implemented a technique which uses three discovery packets, 0.5-1 secs apart, in an app of mine and it seems successful in discovering them all.

**Comment by rudders** [comment]
Thanks for the suggestion. The problem with that approach is that home bridge can't initiate till all accessories are found so we must basically wait until we find them all which is all very hit and miss. Ideally we could asynchronously add accessories as we find them but that's not how HomeKit likes to play. I am considering a rewrite where we use the accessory model and perhaps a helper app for people to build the initial config.json using the sort of re-polling you suggest. I'm going to try some lower level debugging to see if I can find the problem in wemo-client or more likely node-ssdp - wish me luck, but I expect it's Belkin where the issue lies.

**Comment by dwery** [comment]
Within a 5/7 secs timespan I can discover all devices, when multiple SSDP packets are used

**Comment by pdlove** [comment]
I'm getting ready to explore the possibility of getting homebridge and hap-nodejs working where you can register and unregister devices pragmatically. The way I've observed home bridge work while developing on the wink platform plugin it should work.

**Comment by rudders** [comment]
HomeKit doesn't really support it mate. Homebridge gets one chance to register accessories and one chance only.

**Comment by rudders** [comment]
@dwery - are you still struggling to find all your devices?

**Comment by oa-** [comment]
Is there a way to see which devices were discovered?

I have removed homebridge-wemo in order to use you homebridge-platform-wemo plugin, but couldn't even turn on a single Wemo switch.

```
	"platforms": {
		"platform": "BelkinWeMo",
		"name": "WeMo Platform",
		"expected_accessories": "1",
		"timeout": "25",
		"no_motion_timer": "60",
		"homekit_safe": "1"
	},

Is everything I added to the config file. Is that correct?

**Comment by rudders** [comment]
What gets displayed when you start homebridge - the platform plugin reports quite extensively what is going on.

**Comment by AppleTechy** [comment]
@oa- How many wemo devices do you have? And do you have a motion sensor wemo?

**Comment by oa-** [comment]
Thank you for your replies.

I have a single Wemo switch.

It seems that it won't get recognized:

```
`Loaded plugin: homebridge-applescript
Registering accessory 'homebridge-applescript.Applescript'
---
Loaded plugin: homebridge-platform-wemo
Registering platform 'homebridge-platform-wemo.BelkinWeMo'
---
Loaded config.json with 5 accessories and 0 platforms.
---
Loading undefined platforms...
Loading 5 accessories...
[mini] Initializing Applescript accessory...
[Airplay] Initializing Applescript accessory...
[Computer volume] Initializing Applescript accessory...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:`
```

**Comment by AppleTechy** [comment]
Found the problem I think... Your platform section should look like that
    "platforms": [
"platforms": {
        "platform": "BelkinWeMo",
        "name": "WeMo Platform",
        "expected_accessories": "1",
        "timeout": "25",
        "homekit_safe": "1"
    }
]

It seems like your Homebridge for some reason isn't recognizing the "Wemo Platform".

**Comment by rudders** [comment]
Can you provide your complete config.json - Homebridge is skipping the platforms section.

**Comment by oa-** [comment]
Awesome, that was it!

Here's my corrected config.json

```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "123-45-678"
	},

	"platforms": [{
		"platform": "BelkinWeMo",
		"name": "WeMo Platform",
		"expected_accessories": "1",
		"timeout": "25",
		"homekit_safe": "1"
	}],

	"accessories": [{

```


and this is the new output:

```
Registering accessory 'homebridge-applescript.Applescript'
---
Loaded plugin: homebridge-platform-wemo
Registering platform 'homebridge-platform-wemo.BelkinWeMo'
---
Loaded config.json with 5 accessories and 1 platforms.
---
Loading 1 platforms...
[WeMo Platform] Initializing BelkinWeMo platform...
[WeMo Platform] Wemo Platform Plugin Loaded 
[WeMo Platform] Fetching the Wemo Accessories, expecting 1 and will wait 25 seconds to find them.
Loading 5 accessories...
[mini] Initializing Applescript accessory...
[Airplay] Initializing Applescript accessory...
[Computer volume] Initializing Applescript accessory...
[WeMo Platform] Found: Light, type: controllee
[WeMo Platform] Light is false
[WeMo Platform] Discovered 1 accessories of 1 
[WeMo Platform] Woohoo!!! all 1 accessories found.
[WeMo Platform] Initializing platform accessory 'Light'...
```

**Comment by AppleTechy** [comment]
@oa- - Glad you got it to work!
