### ISSUE TITLE
[homebridge-platform-wemo.BelkinWeMo] Ignoring WeMo Platform setup because it is not configured

### ISSUE THREAD

**Issue by wh0di5pl5** [rudders/homebridge-platform-wemo#123]
hey everyone - I just got a Sensibo and added it to my son.config file and it required me to update my home bridge, which made me update my homebridge-platform-wemo too - now, doesn't matter what I do, it says the plug in is not configured and I get this error

[homebridge-platform-wemo.BelkinWeMo] Ignoring WeMo Platform setup because it is not configured

...It then skips the app and doesn't load a god damn thing 😄 

any help?

`{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154",
        "manufacturer": "@nfarina",
        "model": "Homebridge",
        "serialNumber": "0.4.20"
    },
    
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

   "platforms": [
       {
           "platform": "BelkinWeMo",
           "name": "WeMo Platform"
        }
    ],

    "platforms": [
   	{
   	    "platform": "SensiboSky",
   	    "name": "Sensibo",
   	    "apiKey": "xxxxxxxx",
   	    "timeLapse": 5,
   	    "ai": true,
   	    "hideFan": false, 
   	    "hideHumidity": true,
   	    "fixedState" : "auto"			
   	}
    ]
}`

**Comment by devbobo** [comment]
Your JSON config should look more like below, your current config defines `platforms` twice, which means the 2nd one overwrites the first.

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154",
        "manufacturer": "@nfarina",
        "model": "Homebridge",
        "serialNumber": "0.4.20"
    },
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "platforms": [
        {
            "platform": "BelkinWeMo",
            "name": "WeMo Platform"
        },
        {
            "platform": "SensiboSky",
            "name": "Sensibo",
            "apiKey": "xxxxxxxx",
            "timeLapse": 5,
            "ai": true,
            "hideFan": false, 
            "hideHumidity": true,
            "fixedState" : "auto"			
        }
    ]
}
```

**Comment by devbobo** [comment]
closing, please reopen if this is still an issue.
