### ISSUE TITLE
Dimmer Control

### ISSUE THREAD

**Issue by Ledbetter14** [rudders/homebridge-platform-wemo#126]
Just a quick question, were dimmer controls implemented? I saw the PR merged etc, but readme still says no dimming and when i updated I still have no control over dimming level. Am I missing a step or is it not fully implemented yet? Thanks for all the excellent work!

**Comment by airmandan** [comment]
Same question here.  On version 1.3.6.

**Comment by Ledbetter14** [comment]
Clean install sorted it out, I now have full dimmer control.

**Comment by airmandan** [comment]
Huh.  I had tried that previously to no avail, but did so just now and it does indeed work correctly.  Hooray!
