### ISSUE TITLE
Device type

### ISSUE THREAD

**Issue by Red1994** [rudders/homebridge-platform-wemo#127]
Is there any way to customise the device type for wemo maker when set as a momentary switch?

I am using wemo maker as a momentary switch combined with a small DPDT flip/flop relay.  The momentary signal to the flip/flop relay is provided by the wemo maker (or a manual puch button wall switch connected in parallel) which changed the flip/flop relay state from NC to NO or from NO to NC.  I use one of the flip/flop connections for device control and the other for a signal back to the wemo maker sensor.  This set up lets me convert any traditional toggle switch to an on/off push button controlled either by the manual push button or the wemo maker with the wemo maker sensor indicating the current status (on/off).  

I am successfully using the Garage Door function of the Homebridge Wemo plug-in (for my garage door) but would like the same funtionality but to be treated as a switch in Homekit rather than Garage Door.

Is this possible to implement?

thanks

**Comment by devbobo** [comment]
@Red1994 version 1.3.7 should support changing the Maker from a `GarageDoorOpener` to a `Switch`. Follow this [wiki article](https://github.com/rudders/homebridge-platform-wemo/wiki/Change-WeMo-Maker-from-GarageDoorOpener-to-Switch) to change it over.
