### ISSUE TITLE
Maker Status Update

### ISSUE THREAD

**Issue by davidm0708** [rudders/homebridge-platform-wemo#131]
Hi all,

Bit of a newbie, sorry if this is the wrong place for this question.

I use a Wemo maker via HomeBridge to open/close a garage door. However, if a remote is used to open and HomeKit is used to close, or vice versa, the status of of the door in HomeKit is out of sync.

Any idea how I can either force a status change when the door is opened by remote or reset/change the status? 

Thanks

**Comment by DMBlakeley** [comment]
Do you have a sensor (magnetic switch) hooked to the Wemo Maker to indicate that the garage door is closed?  Without this there is no status feedback.
