### ISSUE TITLE
how to ignore devices in configuration

### ISSUE THREAD

**Issue by ebugakov** [rudders/homebridge-platform-wemo#133]
Hi!

do you have an example of the configuration, how can I ignore two WeMo devices in homebridge, while they are working with Apple HomeKit directly via WeMe Bridge?

I've tried to add into configuration something like this, but it seems not working:

"ignoredDevices": [221547K135678],[221547K1532467],

thanks for clarification in advance!

**Comment by devbobo** [comment]
@ebugakov like this...

```"ignoredDevices": ["221547K135678", "221547K1532467"],```

**Comment by ebugakov** [comment]
it works perfectly! thx!
