### ISSUE TITLE
Better handling of TIME-OUT error - ETIMEDOUT

### ISSUE THREAD

**Issue by rudders** [rudders/homebridge-platform-wemo#15]
From issue https://github.com/nfarina/homebridge/issues/457

**Comment by AppleTechy** [comment]
I believe this platform=wemo is the culprit but I am not 100% sure. Though based off what @vincentanthony said about not running the wemo plugin makes me doubt my diagnostic even more. I am also running the nest plugin but Nest isn't the last process running up until the issue, wemo is.

**Comment by rudders** [comment]
homebridge-platform-wemo@0.6.1 should fix this for now. Issue will stay open till wemo-client is released with a fix.

**Comment by rudders** [comment]
homebridge-platform-wemo@0.6.2 released that should address this issue and depends on wemo-client@0.6.2 (version numbers a co-incidence believe it or not!)
