### ISSUE TITLE
WeMo Light

### ISSUE THREAD

**Issue by AppleTechy** [rudders/homebridge-platform-wemo#17]
ttgolf commented on Oct 9, 2015
"Looks like the code was updated a few days ago to support Wemo light bulbs. Just tried it yesterday without any success. Homebridge can't find any light accessories. Anyone has similar issue?"

**Comment by AppleTechy** [comment]
nfarina/homebridge#246 was the old issue but was filed(located) incorrectly

**Comment by rudders** [comment]
Wemo bulbs work fine - are they not being discovered?

**Comment by AppleTechy** [comment]
@rudders you had commented on the old issues 8 days ago...

**Comment by rudders** [comment]
But there is support, we just have this discovery issue. Sonic this is the discovery issue lets just have one issue?

**Comment by AppleTechy** [comment]
issue#12
