### ISSUE TITLE
Not all wemo devices initialized, but all devices found

### ISSUE THREAD

**Issue by IMNotMax** [rudders/homebridge-platform-wemo#2]
Hi, 
First thanks for sharing your great work :)
I have a little issue : not all my wemo devices are initialized, but the platform found them.

See the [pastebin] (http://pastebin.com/Zkgcu1Fn) for the launch messages.
I tried to have a config.json to only initialise the platform (no accessories) and i tried to add wemo accessories too ([last config file](http://pastebin.com/Bi5NEYVy)).
The devices not initialised are 2 wall switches, a standard switch and an insight switch.
I don't understand why only one standard switch is initialized...

Below the list of my devices (if it helps in any way)
- 'Lumiere TV' and 'Le Sapin' are a **standard switches**
- 'Grande Lampe' + 'Lampe Blanche' + 'Lampe Coin' are **bulbs connected through a wemo link**
- 'Interrupteur Intelligent' is an **insight switch**
- 'Prise Exterieure' and 'Lumieres Exterieures' are **wall switches**

My workaround is simply to add home bridge-wemo accessories for the 3 devices not initialized

> FYI :
> - homebridge runs on a OS X 10.7.5
> - all the memo firmwares are up to date
> - homebridge-platform-wemo, homebridge-http, homebridge-ssh, homebridge-wemo are installed
> - npm version =  {npm: '2.14.9',
>   http_parser: '2.3',
>   modules: '14',
>   node: '0.12.9',
>   openssl: '1.0.1q',
>   uv: '1.6.1',
>   v8: '3.28.71.19',
>   zlib: '1.2.8' }

**Comment by rudders** [comment]
Running homebridge-platform-wemo and homebridge-wemo is not really supported - you'll end up with both plugins trying to manage the same device - try removing the accessories and let platform-wemo do all the work.

**Comment by IMNotMax** [comment]
I tried to uninstall the homebridge-wemo pluging, clean the config.json and I have the same result... on OS X.

I also tried to make a fresh install on a LUBUNTU VM (homebridge + dependencies + homebridge-platform-wemo)... and same result (I've tested this fresh install after by installing the homebridge-wemo plugin and the devices were responding)
One of the wemo devices detected is Pool Filter *([WeMo Platform] Found: Pool Filter)*... but I don't have any device named like that....

I also test the ouimeaux script (wemo list) and all the devices are listed... I really don't understand why some devices are seen but not initialized.

**Comment by rudders** [comment]
Currently only Switches and Bulbs are supported. (see other issue in the repo).
I'm updating the plugin for insight switch and will take a look at wall switches too.
Can you tell me based on your list from above which are working and which are not?

- 'Lumiere TV' and 'Le Sapin' are a standard switches
- 'Grande Lampe' + 'Lampe Blanche' + 'Lampe Coin' are bulbs connected through a wemo link
- 'Interrupteur Intelligent' is an insight switch
- 'Prise Exterieure' and 'Lumieres Exterieures' are wall switches

**Comment by IMNotMax** [comment]
[WeMo Platform] Initializing platform accessory 'Lumiere TV'... **as standard switch OK**
[WeMo Platform] Initializing platform accessory 'Le Sapin'...**as standard switch OK**
[WeMo Platform] Initializing platform accessory 'Grande Lampe'...**as bulb OK**
[WeMo Platform] Initializing platform accessory 'Lampe Blanche'...**as bulb OK**
[WeMo Platform] Initializing platform accessory 'Lampe Coin'...**as bulb OK**

The insight and the wall switches are not initialised. 
The "Lumiere TV" switch has been re-initilised and now works (it was found as Pool Filter, I don't know why)

If you need logs, just ask if I can help. 
And now I understand my issue is not an issue :) some devices are not supported for the moment.

My workaround looks good, I use the home bridge-wemo plugin for these devices, and it works great !

**Comment by n3rxstech** [comment]
I am same issue. I have 2 WeMo outlet switches I use for lamps and the Maker for my Garage Door, it finds all 3 but only initializes the switches for the lamps, yet the Maker worked fine for 3 months and still works fine with the WeMo app.

**Comment by rudders** [comment]
Have you done something recently to your configuration? Updated node, homebridge, homebridge-platform-wemo??

**Comment by n3rxstech** [comment]
All I did recently is add a second wall outlet light switch, but with a different name.

 Here is my config section with the WeMo, if I tell it to look for 3 accessories, it doesn't help btw.

 {
                "platform": "BelkinWeMo",
                "name": "WeMo Platform",
                "timeout" : "60"
                }]
}

**Comment by rudders** [comment]
What versions of homebridge and the plugin are you using 
`sudo npm -g ls homebridge`
`sudo npm -g ls homebridge-platform-wemo`

**Comment by n3rxstech** [comment]
pi@homebridge:~/.homebridge $ sudo npm -g ls homebridge
/usr/local/lib
└── homebridge@0.2.16 

pi@homebridge:~/.homebridge $ sudo npm -g ls homebridge-platform-wemo
/usr/local/lib
└── homebridge-platform-wemo@0.6.6 

I also get this error when homebridge starts, not sure if it's an issue.

pi@homebridge:~/.homebridge $ *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?

**Comment by rudders** [comment]
The error is normal so you can safely ignore it.

Please update the plugin `sudo npm install -g homebridge-platform-wemo` it's not tested fully with the latest homebridge so I'd just recommend updating the plugin.

**Comment by n3rxstech** [comment]
still same issue, are you allowed to have more than 1 platform entry? I have my Nest Thermostat in the config as well.

**Comment by rudders** [comment]
Yep - thats not a problem - can you post the complete log from when you start homebridge please. `homebridge -D` please.

**Comment by n3rxstech** [comment]
Odd I have never seen this error before.

pi@homebridge:~ $ homebridge -D
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Loaded plugin: homebridge-nest
Registering platform 'homebridge-nest.Nest'
---
Loaded plugin: homebridge-platform-wemo
Registering platform 'homebridge-platform-wemo.BelkinWeMo'
---
Loaded plugin: homebridge-wemo
Registering accessory 'homebridge-wemo.WeMo'
---
Loaded config.json with 0 accessories and 2 platforms.
---
Loading 2 platforms...
[Nest] Initializing Nest platform...
[Nest] Fetching Nest devices.
[WeMo Platform] Initializing BelkinWeMo platform...
[WeMo Platform] Wemo Platform Plugin Loaded 
[WeMo Platform] Fetching the Wemo Accessories, expecting an unknown number and will wait 60 seconds to find them.
[WeMo Platform] Found: Light, type: controllee
[WeMo Platform] Light is true
[WeMo Platform] Discovered 1 accessories of an unspecified number of accessories 
[WeMo Platform] Found: Hutch, type: controllee
[WeMo Platform] Hutch is false
[WeMo Platform] Discovered 2 accessories of an unspecified number of accessories 
[WeMo Platform] Found: Door, type: Maker
[WeMo Platform] Light binaryState: off
[WeMo Platform] Hutch binaryState: off
[Nest] Temperature unit for Living Room is: Fahrenheit
[Nest] Current temperature for Living Room is: 71 F
[Nest] Current humidity for Living Room is: 30%
[Nest] Target temperature for Living Room is: 68 F
[Nest] Target heating for Living Room is: Heating
[Nest] Initializing platform accessory 'Living Room'...
[WeMo Platform] Initializing platform accessory 'Light'...
[WeMo Platform] Initializing platform accessory 'Hutch'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 987-65-432 │     
    └────────────┘     
                       
Homebridge is running on port 51826.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:58:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:138:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:437:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:50:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:229:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at null._onTimeout (/usr/local/lib/node_modules/homebridge-platform-wemo/index.js:113:13)
    at Timer.listOnTimeout (timers.js:89:15)

**Comment by rudders** [comment]
Looks like you already have homebridge running in the background.

**Comment by n3rxstech** [comment]
I killed it and started it again, no error this time, but still no Door

**Comment by n3rxstech** [comment]
Here is my full config.json minus my login for my Nest of course.

pi@homebridge:~/.homebridge $ cat config.json 
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "987-65-432"
	},

	"platforms": [{
		"platform": "Nest",
		"name": "Nest",
		"token": "c.tibCy42jjS318zOG5rSnGUkjltdWWzzV0baszPQzsnaR3xWBLLHu5vVNvV5uuwYwMFxw0fPFvpUwfhdP8wB75RSqRrjvn6fXQ26BQDqgnNOfpK6FGT9UPcFhpJu3qo8894Xg4hdnyMKHmi6Q",
		"username": “XXXXXXX”,
		"password": “XXXXXXX”
                },
                {
		"platform": "BelkinWeMo",
		"name": "WeMo Platform",
		"timeout" : "60"
                }]
}

**Comment by rudders** [comment]
It finds the Maker but never reports it as discovered because the plugin version currently released doesn't support Wemo Makers - it should never have worked. The Maker support is in an unreleased version of the plying we'er working on for Homebridge 0.3.

**Comment by rudders** [comment]
https://github.com/rudders/homebridge-platform-wemo/issues/28

**Comment by n3rxstech** [comment]
ok, maybe it was working before because I was using both WeMo platform and accessory plugins. the WeMo accessory, homebridge-wemo does support it according to the info on GitHub

**Comment by rudders** [comment]
homebridge-wemo will support a Maker as a simple switch this is true - just reinstall it and reconfigure - the two plugin's should be okay in this configuration (I think)

**Comment by n3rxstech** [comment]
yeah I put the door back in as an accessory item using the other plugin and now all my WeMo items seem to work again. Thanks!

**Comment by n3rxstech** [comment]
nope, I stand corrected, I can only seem to get 2 items to work at a time, ugh
