### ISSUE TITLE
Return "male"

### ISSUE THREAD

**Issue by stanthewizzard** [rudders/homebridge-platform-wemo#20]
Hello

When I activate a light switch
Siri tells me
"Light male"
not activitated or on

**Comment by rudders** [comment]
Have you read https://github.com/nfarina/homebridge/wiki/Siri-commands
Does it all work with your HomeKit app okay?
Is "Male" the name of the device?
Is it a switch or bulb?
What is the sentence you say to Siri vs the name/type of device etc,

**Comment by stanthewizzard** [comment]
Yes
Yes
Nope it's "lampe"
It's a wemo switch for a lamp
Switch on name of the wemo device

Thanks for your help

**Comment by rudders** [comment]
It's a Siri Homekit issue I expect. If it works in HomeKit it's an issue between Siri and HomeKit? Possible it's a language/locale issue. I assume Siri works for you otherwise though.

**Comment by IMNotMax** [comment]
I can confirm, Siri make this error in French (French from France, I did not test Canadian French).
it's a known Siri issue (I found references in french forums around Homekit) and it's funny :)
"Ça y est, les Lumières sont males" is a common phrase!

**Comment by rudders** [comment]
Thanks @IMNotMax - not sure I understand the intricacies of you response but sounds like it's HomeKit not this plugin for sure?

**Comment by rudders** [comment]
I'm closing this as I've not had any feedback to suggest it's a plugin problem rather than a Siri problem
