### ISSUE TITLE
Specify subnet scan

### ISSUE THREAD

**Issue by picnicbob** [rudders/homebridge-platform-wemo#22]
When connected to multiple network interfaces it looks like only the first is being scanned. On my Mac I often connect to a VPN that has network priority over my LAN, causing the LAN wemo devices to go undiscovered.
It would be nice to be able to set a specific subnet to scan in the config file.

**Comment by rudders** [comment]
I understand and appreciate the issue - Discovery is processed using node-ssdp within wemo-client and my networking knowledge  may not be up-to-the task but I'll take a look.

**Comment by rudders** [comment]
Had a look around - this issue in node-SSDP seems like an indicator that it's a bit of a known issue. Binding to your wifi for discovery would be one answer, but a bad on in my experience. But could easily be hacked into your local copy of Wemo-client if you wanted to try it. 

On my Mac mini I wrap logic around certain network operations like restarting Homebridge that downs the VPN first and then restarts it after - might be a work around to try.

**Comment by picnicbob** [comment]
Ok, seems like it's not worth the effort. I've set up different network locations to get around the issue for now.

**Comment by amitgandhinz** [comment]
im curious if this is my current issue now.  

I seem to have resolved the issue i had in #24 where my Wemo app seems to be consistently showing the light switch.  But now the homebridge service can no longer find the wemo (im using the new wemo-platform now also).  

My setup is wemo on Wifi, 
RPi running homebridge on Ethernet to Router.
Ubiquiti AP, AT&T uVerse Router.

Running a third party SSDP client looked like it would only look at the eth0 network interface and thus could not see anything connecting to the wifi network.  Im still new to SSDP so also likely i ran the commands incorrectly.

**Comment by picnicbob** [comment]
Have you tried removing the ~/.homebridge/persist directory? I've found that after making a change to a HomeKit accessory's name I needed to clear what I assume is some sort of cache stored in there and reconfigure HomeKit on my device. I'm not sure if this is the right thing to do, but it might help you out.

**Comment by rudders** [comment]
@amitgandhinz - are your ethernet and wifi devices handed ip addresses from the same subnet? SSDP should work fine if the router is bridging between networks properly. I use RPi->etc->AirportExtreme->wifi->wemo devices fine - but when RPi was on Eth and Wifi my milage varied

**Comment by amitgandhinz** [comment]
@picnicbob yes i tried deleting the persist directory.  Doesnt seem to help.
@rudders yes the ip addresses are all issued by the uverse router

**Comment by rudders** [comment]
Are they all on the same subnet - same first three parts if up address? e.g 192.168.0.xxx

**Comment by amitgandhinz** [comment]
yes.  RPi is 192.168.1.144 and Wemo Light Switch is 192.168.1.134

**Comment by rudders** [comment]
Quick search on that router and uPNP gets a lot of hits - I suspect there might be an issue with uPNP (SSDP) and your router - perhaps do some research to make sure your router is appropriately configured to bridge the LAN and WLAN correctly (or get the RPi on the WLAN)

**Comment by amitgandhinz** [comment]
Thanks for pointing me in that direction, i think you are right.    I am going to see if i can use my Timecapsule to do the NAT and have my uVerse router passthrough to it. Unfortunately it looks like uVerse routers dont support uPNP so I am hoping i can let the Timecapsule handle that stuff.  I will let you know how i get on.

**Comment by rudders** [comment]
Not supporting uPNP and not acting as a bridge aren't necessarily the same thing, well they're totally different but experience tells me where there's one "feature" missing others may well follow.
