### ISSUE TITLE
wemo light switch not found

### ISSUE THREAD

**Issue by amitgandhinz** [rudders/homebridge-platform-wemo#24]
Hi

I run into intermittant issues where my wemo light switch can no longer be found on the network.  This may not be an issue specifically with the homebridge plugin as I also get the device not found on the wemo app.

Remote access to the switch works fine via the Wemo app. Local wifi access does not.

My network AP broadcasts with an SSID that does only 2.4Ghz, and then another SSID that does only 5Ghz.  The Wemo is connected only to the 2.4Ghz SSID.  My RPi is hardwired ethernet to the same network as the AP.

Any ideas?  I know this probably isnt a homebridge issue, but am hoping you may be able to help if you ran into this issue yourself.

What confuses me is I will get it working sometimes, then the next day its gone again.  Very frustrating.

This is the error logged:

 Jan 16 10:58:22 raspberrypi homebridge[6314]:at, 16 Jan 2016 15:58:22 GMT node-ssdp:client Sent M-SEARCH request: { message: 'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:Belkin:service:basicevent:1\r\nMAN: "ssdp:discover"\r\nMX: 3\r\n\r\n' }

**Comment by rudders** [comment]
If I had a dollar for every time a wemo device was not found on my network... 

If you've got problems with the Wemo app (which I do to) then it's just the quirkiness of the Wemo. There is a Homebridge slack https://homebridgeteam.slack.com/home team with a Homebridge-Wemo channel where you could ask this but also belkin support forums are well used and may have some advice.

We're implementing some changes later in the month to try multiple times to find things on the network. This could improve things.

The best advice I have for wifi is to get "wifi scanner" for your Mac and look at how many networks are sharing the frequencies you're using. Then update your router to specify a channel which is least congested.

[WiFi Scanner Mac OS X, Snow Leopard, Lion, Mountain Lion, Mavericks](http://accessagility.com/products/wifi-scanner.html)

**Comment by amitgandhinz** [comment]
Thanks.  I know the issue isnt my wifi itself, as i dont get much noise and my other devices work fine and perform well.

Doing more research, it looks like the cause of the issue is due to wemo changing their port number.

running a curl command for a port between 49152-49154 tends to yield results

    $ curl <wemo ip address>:<port>/setup.xml

According to some reports, its when wemo decides to change its port, the problem appears.  The wemo app is stuck on the wrong/older port, and thus cant rediscover it.  I am guessing its an issue with the service discovery not finding the new port.

Based on this theory, I am going to wait a few days, see how the port is actually changing for me by running the above curl request, and determine if this is the cause.  This may be something the patch to retry multiple times can help with - ie if the wemo isnt found, cycle through the possible ports?

I'll leave my findings here.

Thanks for the help.

**Comment by rudders** [comment]
Nice work. Thanks for the feedback - keep in coming and please get on the slack community - it could use your growing knowledge.

We may need to update the plugin to "rediscover" also. Some changes in iOS 9.3 will allow us to get much smarter about this in the future also.

**Comment by amitgandhinz** [comment]
okay, new thing i discovered today.  I removed my secondary SSID, so now my AP only broadcasts a single SSID on 2.4Ghz.  This seems to have fixed the issue (i will observe over the next few days).

Im not sure why having a second SSID (even if nothing is connected to it) would impact this.  It may be my AP (Ubiquiti AC-LITE) that could be confusing packets for multicast messages.  Im not too familiar how that works.

Nevertheless, a single SSID broadcast seems to be working for now.  Lets see if it continues to work over the next few days. 

 If it continues to work then i will start investigating why having a second SSID would impact this.

**Comment by Azza1979** [comment]
Hi Rudders very new to github and using it to control home kit. My question is i use the wemo maker to open my garage door  and have a sensor on it so it knows if the sensor is triggered or not. Is there anyway of putting this info somewhere so i can ask siri if the door is triggered or not. I hope that makes sense.

**Comment by amitgandhinz** [comment]
Okay, Wemo app now seems to be working more consistently.  The issue ended up being a combination of things

- didnt like multiple SSID's
- there were firewall rules setup by default by my AT&T uVerse Router that were dropping packets.  Removing some of these rules got the app working a bit more consistently.  But now the homebridge service cant find it (go figure).

**Comment by rudders** [comment]
Thanks for updating and closing.
