### ISSUE TITLE
Unable to turn off WeMo Insight Switch

### ISSUE THREAD

**Issue by aaronwolen** [rudders/homebridge-platform-wemo#27]
I have a Wemo light switch and a Wemo insight switch on my network. The plugin works perfectly for the light switch. However, the insight switch can only be turned on using siri. Whenever I try to turn if off I'm told Siri can't get a response from this device. No errors are thrown in the log (even with debugging on) so I'm not sure how to troubleshoot further.

Any thoughts?

**Comment by rudders** [comment]
Can you confirm versions for me please `npm ls wemo-client`

**Comment by rudders** [comment]
Sorry `npm ls -g wemo-client`

**Comment by aaronwolen** [comment]
```
/usr/local/lib
└─┬ homebridge-platform-wemo@0.6.4
  └── wemo-client@0.6.2
```

**Comment by rudders** [comment]
Thanks - lack of errors is a problem to diagnose but it might be an error in wemo-client we're not seeing. Can you run with DEBUG=wemo-client please and see if we get any more data to work on.

**Comment by aaronwolen** [comment]
Not sure if it's relevant but I just realized the insight can be turned on and off using MyHomeTouch.

Rerunning with `DEBUG=wemo-client` reveals incoming requests are being sent to the insight about 1 per second; my log is filled with entries like this:

```
Jan 23 18:13:26 raspberrypi homebridge[4041]: Sat, 23 Jan 2016 23:13:26 GMT wemo-client Incoming Request for uuid:Insight-1_0-22...: <e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
Jan 23 18:13:26 raspberrypi homebridge[4041]: <e:property>
Jan 23 18:13:26 raspberrypi homebridge[4041]: <InsightParams>1|1453590001|804|25981|510131|1209600|828|843905|356872637|6984905318|8000</InsightParams>
Jan 23 18:13:26 raspberrypi homebridge[4041]: </e:property>
Jan 23 18:13:26 raspberrypi homebridge[4041]: </e:propertyset>
```

**Comment by rudders** [comment]
This is the insight informing us about consumption - I don't have one so can't test but @devbobo who added that code might be able to add some thoughts to this. i.e. I think this is normal - complete log would be handy please.

**Comment by devbobo** [comment]
@rudders `on` and `off` commands work fine for all my insight devices

**Comment by aaronwolen** [comment]
Thanks, guys. For the record, the Insight's firmware version is `WeMo_WW_2.00.10062.PVT-OWRT-Insight`. 

You can see a complete log [here](https://gist.github.com/aaronwolen/03d15047df94dbbbe0aa).

I launched homebridge with the Insight (called "Maxs heater") turned off. After everything initialized I used Siri to turn on the insight, waited a few seconds, then asked if the insight was turned on, then tried to turn it off but, as usual, that didn't register.

I also tried completely deregistering homebridge from HomeKit and reinstalling the wemo plugin but this produced the same result.

**Comment by devbobo** [comment]
@aaronwolen i'm on the same firmware version, looking at your log file, I see....
```Jan 24 19:30:58 raspberrypi homebridge[13396]: [WeMo Platform] setOn: Maxs Heater to on```

but I don't see a corresponding call to, which would indicate the HomeKit has tried to turn off Max's heater...
```[WeMo Platform] setOn: Maxs Heater to off```

**Comment by aaronwolen** [comment]
That's the problem. When I issue a call to turn it off Siri doesn't recognize the device and, it seems, fails to pass on the request. It's very consistent. I can always turn it on, I can always ask if it's on or off but I can never turn it off. 

I'm not sure where in the protocol this issue arises, is it possibly unrelated to homebridge?

**Comment by rudders** [comment]
Have you tried changing the name off the wemo - perhaps the combination of it's name and the off command are a problem.

**Comment by aaronwolen** [comment]
Wow, good call. It's definitely peculiar about naming: `Outlet` works, `Maxs Heat` works but `Heater` doesn't.

Thanks for helping me troubleshoot this issue, guys. I really appreciate it.

**Comment by rudders** [comment]
No worries - glad you got it worked out!
