### ISSUE TITLE
Add Wemo Maker Support

### ISSUE THREAD

**Issue by rudders** [rudders/homebridge-platform-wemo#28]
wemo-client supports this so should't be too hard.

**Comment by devbobo** [comment]
@rudder: on the surface, no...it's simple and very straightforward.

But given that the flexibility of the device, it could be defined as a number of different HAP services. It could be a `Service.GarageDoorOpener`, `Service.StatefulProgrammableSwitch` or some other service that a user dreams up.

**Comment by Azza1979** [comment]
Hi 
Ive been using the wemo platform but it won't add my wemo makers that i use to open the garage doors but i have been using them under accessories. My problem is that while doing it this way it crashes homebridge but if i remove the makers from the accessories list  it doesn't  crash. Im using the mac terminal would i be better off using a raspberry pi ?

This is what my json file looks like. Can you suggest something.
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },

  "description": "The Borrows Home config",
  "platforms": [
        {
          "platform": "BelkinWeMo",
          "name": "WeMo Platform",
          "expected_accessories" : "17",
          "timeout" : "30",
          "no_motion_timer": "60",
          "homekit_safe" : "1"
        }   
    ],
  "accessories": [
    {
      "accessory": "WeMo",
      "name": "Dads Shed",
      "description": "Garage Door.",
      "wemo_name": "Dads Shed"
    },
    {
     "accessory": "WeMo",
      "name": "Garage Door",
      "description": "Garage Door.",
      "wemo_name": "Garage Door"
    }
  ]
}

**Comment by rudders** [comment]
Currently homebridge-platform-wemo does not support wemo maker - this will change shortly.
homebridge-wemo seems to work with maker but is untested and I'm putting all my limited resources into the platform plugin currently.

If you provide details of the crash of the homebridge-wemo I might be able to fix it but without details of the crash I have no idea what the problem might be.

**Comment by detroittigers** [comment]
How are things progressing with supporting the maker?

**Comment by kenderson** [comment]
Just checking in on support for the Maker? The plugin is awesome, it's just missing this one component for me.

Thanks!

**Comment by devbobo** [comment]
@detroittigers @kenderson I'd suggest that you check out this branch of the plugin, it has WeMo Maker support...
https://github.com/rudders/homebridge-platform-wemo/tree/persist-homekit

**Comment by kenderson** [comment]
@devbobo Thanks for the branch reference! Quick question - I'm now used to installing/updating from NPM - whats the suggested workflow to pull from a specific Github branch?

**Comment by tmur11** [comment]
@devbobo I took a look at the branch and it's quite a bit different code. Is there any reason we can't merge this into the master branch?

@driskell you should join the homebridge slack team. Perhaps you could give us your 2 cents on this.

**Comment by devbobo** [comment]
@tmur11 I would love it to be merged into the master branch, and that was my intent when I rewrote it. But @rudders has been AWOL for several months...so who knows.

@kenderson you could try `npm install https://github.com/rudders/homebridge-platform-wemo/tree/persist-homekit`

**Comment by devbobo** [comment]
Supported since version`1.0.0`
