### ISSUE TITLE
Insight switch not supported?

### ISSUE THREAD

**Issue by DJay1** [rudders/homebridge-platform-wemo#3]
First thanks for your work.
At the moment I still use your homebridge-wemo with my two insight switch. Works great.

Unfortunately with this new homebridge-platform-wemo the two switches are not showing up on my iOS. When I rund homebridge they are up in the config.json but not to see as a device anywhere.

For the moment I keep staying with homebridge-wemo but I had the hope to see the insight switches in HomeKit as a power meter to check the consumption.

**Comment by rudders** [comment]
I haven't checked if the two modules are compatible.
I think an Insight Switch operates much the same as a Power plug Switch so I can add it to the code and you can test it if you're game.

**Comment by henryblackman** [comment]
I'd be game to test... I only have insight switches in my home.

**Comment by IMNotMax** [comment]
Hi, I'm game to test it, I have and insight and 2 wall switches :)

**Comment by benmazin** [comment]
Thanks for your work, I can confirm Wemo insight switches now work!

**Comment by IMNotMax** [comment]
I made the update this night and it works !
But I lost a standard switch... the same, as usual... I think I will restore this wemo switch with the factory settings and test again.

**Comment by rudders** [comment]
I've found that sometimes they don't get discovered properly - restart homebridge a few times.

**Comment by henryblackman** [comment]
This works a treat for me... Now all the insight plugs (6) show up pretty quickly.  The switching off and on via Siri seems significantly faster and much more reliable to me too.  Thanks for your hard work!

**Comment by IMNotMax** [comment]
I confirm. It's faster and find all devices excepted the wall switches. 
Thanx a lot !

**Comment by rudders** [comment]
Awesome - wall switch next....
