### ISSUE TITLE
Cannot find any devices

### ISSUE THREAD

**Issue by alexandrupaulpopa** [rudders/homebridge-platform-wemo#30]
Hi,

I've installed the WeMo homebridge module and it cannot detect whatsover the 6 wemo devices in the network

Here is the config:

  {
                  "platform": "BelkinWeMo",
                  "name": "WeMo Platform",
                  "expected_accessories" : 6,
                  "timeout" : "120",
                  "no_motion_timer": "60",
                  "homekit_safe" : "1"
                }

Here is the output:

[WeMo Platform] We have timed out and only discovered 0 of the specified 6 devices - try restarting homebridge or increasing timeout in config.json
[WeMo Platform] and you have indicated you'd like to keep your HomeKit config safe so we're crashing out
/usr/local/lib/node_modules/homebridge-platform-wemo/index.js:110
                    throw new Error("homebridge-wemo-platform has intentially bought down HomeBridge - please restart - sorry but it's your HomeKit configuration we're protecting!");
                    ^

Error: homebridge-wemo-platform has intentially bought down HomeBridge - please restart - sorry but it's your HomeKit configuration we're protecting!
    at null._onTimeout (/usr/local/lib/node_modules/homebridge-platform-wemo/index.js:110:27)
    at Timer.listOnTimeout (timers.js:92:15)

Any advices?

**Comment by rudders** [comment]
I have just uploaded a very simple app to try and help debug these situations - try it here https://github.com/rudders/wemo-discover.git

# Does the wemo app find the devices okay?
# Are the wemo devices on the same network subnet as the homebridge server?
# What is your homebridge server running on (platform)?
# If you can find the IP address of any of the devices can you ping them from your homebridge server?

**Comment by alexandrupaulpopa** [comment]
Issue fixed, after the latest wemo update they were no longer discoverable in the LAN, factory reseted them issue solved

**Comment by rudders** [comment]
Excellent news

**Comment by Gav2905** [comment]
Hi,

I cant get homebridge to find any devices, this is my comfig.json:
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "123-45-678"
	},

	"platforms": [{
		"platform": "BelkinWeMo",
		"name": "WeMo Platform",
		"expected_accessories": "7",
		"timeout": "25",
		"homekit_safe": "1"
	}]
}


I've tried the debug app bit can't get that to run, any ideas where I might be going wrong?

**Comment by tekuonline** [comment]
@Gav2905 Try this?
https://github.com/rudders/wemo-discover

**Comment by Gav2905** [comment]
Hi, I cant get this to run for some reason

**Comment by tekuonline** [comment]
What happens when u try to run?

**Comment by Gav2905** [comment]
Hi

This is what happens:

gavin@ubuntu:~$ sudo npm install https://github.com/rudders/wemo-discover.git

/home/gavin
└── wemo-discover@1.0.1  (git+https://github.com/rudders/wemo-discover.git#2b19de92303569a92d9de7c6f47b55421dca6cd9)

npm WARN enoent ENOENT, open '/home/gavin/package.json'
npm WARN gavin No description
npm WARN gavin No repository field.
npm WARN gavin No README data
npm WARN gavin No license field.
gavin@ubuntu:~$ 
gavin@ubuntu:~$ cd wemo-discover
bash: cd: wemo-discover: No such file or directory

**Comment by tekuonline** [comment]
Looks like a npm permissions issue. Can u post the log of when running homebridge?

**Comment by Gav2905** [comment]
gavin@ubuntu:~$ homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
Loaded plugin: homebridge-platform-wemo
Registering platform 'homebridge-platform-wemo.BelkinWeMo'
---
Loaded plugin: homebridge-wemo
Registering accessory 'homebridge-wemo.WeMo'
---
Loaded config.json with 0 accessories and 1 platforms.
---
Loading 1 platforms...
[WeMo Platform] Initializing BelkinWeMo platform...
[WeMo Platform] Wemo Platform Plugin Loaded 
[WeMo Platform] Fetching the Wemo Accessories, expecting 7 and will wait 120 seconds to find them.
[WeMo Platform] We have timed out and only discovered 0 of the specified 7 devices - try restarting homebridge or increasing timeout in config.json
[WeMo Platform] and you have indicated you'd like to keep your HomeKit config safe so we're crashing out

/usr/lib/node_modules/homebridge-platform-wemo/index.js:110
                    throw new Error("homebridge-wemo-platform has intentially 
                          ^
Error: homebridge-wemo-platform has intentially bought down HomeBridge - please restart - sorry but it's your HomeKit configuration we're protecting!
    at null._onTimeout (/usr/lib/node_modules/homebridge-platform-wemo/index.js:110:27)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
gavin@ubuntu:~$

**Comment by tekuonline** [comment]
Is WeMo app detecting all the devices on network? Also could be a network config but not sure why any of your devices are not showing up!  May be, @rudders can help you here?

**Comment by Gav2905** [comment]
Yeah no problems in the iOS WeMo app all devices showing up and controllable.

**Comment by rudders** [comment]
Where does npm install local (non global) packages on Ubuntu? Try npm root. And try using npm install WEMO-discover not sudo, should only need sudo on global plugins.

**Comment by rudders** [comment]
Is your ubuntu server a VM by any chances? Is the VM bridged to your LAN? I'd say that server can't see the network segment the wemos are in

**Comment by Gav2905** [comment]
Hi Rudders,

Yes it is a VM I'm running and it is bridged, so think you've hit the nail on the head. I'm currently doing a fresh install of OSX at the moment so when I'm up and running will give it another try.  Thanks for the support.

**Comment by AppleTechy** [comment]
This issue might be the VM. I had tried running it on a VM originally and I
couldn't get it to find the wemos. As soon as I switched to the normal os I
had no problems with node finding the Wemos

**Comment by Gav2905** [comment]
Hi, I now have this up and running on on my standards OS not using VM.  All WeMo devices found and all working great. Thanks for all the help and support. If I have VPN turned on would this stop Homebridge working?

**Comment by rudders** [comment]
Glad you're up and running. VPN will likely stop homebridge initiating properly and will likely cause status monitoring to fail, you may retain some control over devices,
