### ISSUE TITLE
Crashing homebridge when adjusting wemo bulb brightness from outside homekit

### ISSUE THREAD

**Issue by rudders** [rudders/homebridge-platform-wemo#31]
As reported by @IMnotmax. Logs to follow.

**Comment by IMNotMax** [comment]
Was not able to reproduce the crash... but I've updated the firmware of my demo yesterday... and the app (WSwitch) I use had an update too... maybe this solve the problem...

Here my first test : 
[homebridge.err.txt](https://github.com/rudders/homebridge-platform-wemo/files/146580/homebridge.err.txt)

[homebridge.log.txt](https://github.com/rudders/homebridge-platform-wemo/files/146582/homebridge.log.txt)

The only issue is the WSwitch app can create an infinite loop when you use the brightness often... not a homebridge issue, but this bug made my test (up/down/up/down... until I unplugged the bridge). Then you'll see in the log that the bridge does not respond at the end.. all my light were blinking... weird situation :)

I let the DEBUG=* homebridge -d running to the next crash :P

**Comment by rudders** [comment]
Next crash! What next crash??? There will be no "next" crash ;)
Cheers
