### ISSUE TITLE
Keep getting an error message

### ISSUE THREAD

**Issue by Gav2905** [rudders/homebridge-platform-wemo#32]
Hi,

I love the look of this project and I think I've setup everything correctly, however I keep getting the following error message:

Loaded plugin: homebridge-wemo
Registering accessory 'homebridge-wemo.WeMo'
---

/usr/lib/node_modules/homebridge/lib/server.js:136
  var username = config.bridge.username;
                              ^
TypeError: Cannot read property 'username' of undefined
    at Server._loadConfig (/usr/lib/node_modules/homebridge/lib/server.js:136:31)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:25:23)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

Any ideas what I'm doing wrong?

**Comment by AppleTechy** [comment]
What does you config.json look like? The compete file. My guess without
seeing it you might have missed the entire Bridge section in the config. Or
you have an invalid username set in the bridge section.

**Comment by Gav2905** [comment]
Hi,

Thanks for getting back to me so quickly, I'm really a novice at this.  This is the config.json file:
{
	"platforms": [{
		"platform": "BelkinWeMo",
		"name": "WeMo Platform",
		"expected_accessories": "0",
		"timeout": "25",
		"no_motion_timer": "60",
		"homekit_safe": "1"
	}]
}


Do I need to add anything else to the file?

**Comment by AppleTechy** [comment]
Yep check out the example config included with homebridge. You need to have
the entire bridge sections at the beginning of the config.json. If you need
any more help let me know

**Comment by Gav2905** [comment]
Hi  AppleTechy,

Thanks for the update, I've added in the bridge section to the config.json and it seems to run fine in terminal and gives me the pin.  I can also see homebridge in  my iOS app but it won't add, it doesn't even let me enter the pin.

Any help is very much appreciated.

**Comment by rudders** [comment]
Depends on the app you're using - look for "enter pin manually" on the screen for adding accessories

**Comment by rudders** [comment]
On the Homebridge GitHub homepage is a Slack button which will invite you to the slack community which is a great place for some of these early debugging.
