### ISSUE TITLE
wemo switch crashed everyday

### ISSUE THREAD

**Issue by fildy** [rudders/homebridge-platform-wemo#34]
hi,
I have wemo motion, switch and sight installed for my homekit.
everyday, my homebridge is crashing due to wemo
I have this kind of error message

[WeMo Platform] HTTP Error (EHOSTUNREACH) occurred (re)subscribing to Wemo Device (laundry - 192.168.10.139:49155), retrying. uuid:Insight-1_0-221450K1200538                                                             
[WeMo Platform] HTTP Error (EHOSTUNREACH) occurred (re)subscribing to Wemo Device (lr.light - 192.168.10.22:49154), retrying. uuid:Socket-1_0-221412K1100C7D                                                              
[WeMo Platform] HTTP Error (EHOSTUNREACH) occurred (re)subscribing to Wemo Device (laundry - 192.168.10.139:49155), retrying. uuid:Insight-1_0-221450K1200538                             

everyday, the wemo that have problems is changing.

Is there any way to avoid the crash?

**Comment by rudders** [comment]
Your WEMO is becoming unreachable on the network so the plugin looks for it on other ports.

Is it just this laundry device that has issues? What sort of device is it. These errors won't crash homebridge. The device will stop working but homebridge should keep ruining

**Comment by fildy** [comment]
What i mean crashes is all trigger related to wemo become not responding,
affecting not only wemo which unreachable.
But i read that it's often wemo become unreachable. Dont know how to solve
the issue..

**Comment by rudders** [comment]
Can you provide a comprehensive log from starting homebridge to when the issue occurs please?
Have you updated to latest homebridge and plugin? EHOUSTUNREACH is usually the WEMO restarting for some reason and changing ports. Can you reliably reproduce the problem somehow?

**Comment by fildy** [comment]
hi,

yes, I can reproduce the problem.
I use the latest homebridge and plugin

[homebridge_log.txt](https://github.com/rudders/homebridge-platform-wemo/files/160247/homebridge_log.txt)

thanks for the help and respond

**Comment by fildy** [comment]
Hi,
I find in one of the website : 

Although it is possible to talk with WeMo devices directly from within Openremote as described in the MQL Service's blog post, this method is highly unreliable. WeMo devices use UPnP protocol while Openremote interface was done in the lower HTTP layer, missing therefore extras which UPnP offer, most importantly automatic device discovery and configuration. This leads to problems that manually configured WeMo devices disappear after few days and the configuration procedure need to be repeated manually every few days. This is of course not desirable, therefore a 3rd party open source WeMo API is used to address these issues. This API is called Ouimeaux and can be installed from here.

Is it possible to add this kind of method (connect to wemo using 2nd layer) to improve realibility?

**Comment by rudders** [comment]
We use UPnP for discovery of the devices and the http interface for control in the same way that the wemo apps do. Belkin are continually adding code to try and stabilise the platform as frequent disconnects are very common on the welkin wemo forums.

When the device becomes unreachable can you try and ping it `ping 192.168.10.139` from the Homebridge server and/or other computers to see if it's still alive at that IP address - maybe it's jumping to a new IP address for some reason? Do you have short DHCP leases on your network? Could something else be trying to grab this IP address?

**Comment by fildy** [comment]
i think the main problem is the common disconnection issues from wemo. even with the wemo apps, it often happen. from what you explain, what i can do is set the wemo to manual ip in my router. it helps not jumping to new ip, but not solving the common disconection issue.

the big problem with wemo for homekit, since it can be use as trigger, it collect the status very frequent. when the wemo missing due to disconnection, it makes homekit become not responsive if the wemo is part of the trigger

thanks for your effort to bring wemo to homebridge. but wemo have limitation with current connection approach to homekit or firmware that lead to realibility.
