### ISSUE TITLE
How to exclude specific wemo switch?

### ISSUE THREAD

**Issue by fildy** [rudders/homebridge-platform-wemo#37]
Hi,

I want to exclude some of my wemo switch from being listed by this pluggin.
The reason is because some of my wemo switch often dropped its connection.
I still use it to connect with iFTTT

thanks for the help or sugestion

**Comment by rudders** [comment]
Currently this is not supported and would need to an enhancement. Can we resolve the dropped connection issue? Can you provide details of the error and the crash and the effect?

**Comment by fildy** [comment]
hi,

dropped connection often happen. the effect make homekit become not responsive due to the wemo is part of the trigger

**Comment by rudders** [comment]
Any clues on why the connection drops?

**Comment by fildy** [comment]
Just suspicion with the cause of the drop:
- the switch that always drop somehow located in the most far location from
the router. it's located in the bathroom (laundry machine).
- I use wifi repeater to solve it and seems this not working smoothly with
wemo. since I remove the repeater, I rarely found the dropping issue.
Sometime still happen, but I think that's part of the wemo issue

**Comment by rudders** [comment]
That sounds very much like the problem. WEMO and wifi extenders aren't good friends in my experience. Unlike the WEMO iOS app we're constantly monitoring/listening to the WEMO switch so we're a bit sensitive to it being available and what will be happening is that the WEMO switch will loose connection to the Internet so will be changing ports as well so we have lots of issues to deal with. Not much we can do about it in code as HomeKit users expect the current state of the switch to always be accurate so we need a reliable connection to it.

**Comment by fildy** [comment]
but then, is it possible to exclude this wemo switch from the wemo platform plugin? I know I can manage it using the old wemo plugin, but the old pluggin cannot recognize the wemo motion sensor, or it can?

**Comment by rudders** [comment]
Correct. 
Is it a switch or a bulb you want to exclude. I could probably add an exclude function but would be hard for individual bulbs. Equally just unplug the switch, start homebridge and then turn it on after homebridge has finished initialising.

**Comment by fildy** [comment]
it's switch plug. the problem, sometimes homebridge need to be restart. It's painfull to unplug 4 switch everytime I restart

**Comment by devbobo** [comment]
@fildy you should try [this branch](https://github.com/rudders/homebridge-platform-wemo/tree/persist-homekit) of the plugin, it's been rewritten with new Homebrdige features released in version 0.3.0, which include device persistance, so WeMo plugin dropping offline shouldn't cause any problems.

**Comment by fildy** [comment]
Thanks for the info

**Comment by devbobo** [comment]
This shouldn't be required with the new `1.0.0` release.
