### ISSUE TITLE
Homekit not finding the homebridge

### ISSUE THREAD

**Issue by prich987** [rudders/homebridge-platform-wemo#38]
I had it working on a Mac and wanted to switch to an RPi and now I can't get the RPi nor the Mac to show up in the homekit app. Any ideas on how to resolve this?

**Comment by rudders** [comment]
usual techniques are to change the `pin` in `config.json` and delete `~/.homebridge/persist` and restart - make sure different `pin` for each instance

**Comment by rudders** [comment]
Installation instructions https://github.com/rudders/homebridge-platform-wemo/blob/master/README.md#installation

**Comment by prich987** [comment]
Thanks, that did the trick.

**Comment by rudders** [comment]
No Problem.
