### ISSUE TITLE
Failing to install on Beaglebone black

### ISSUE THREAD

**Issue by prich987** [rudders/homebridge-platform-wemo#39]
I have tried to install homebridge-platform-wemo on a Beaglebone Black and get the following error. Any ideas on how to resolve this?
Thanks,
Paul

debian@beaglebone:~$ sudo npm install -g homebridge-platform-wemo
npm WARN engine homebridge-platform-wemo@0.6.9: wanted: {"node":">=0.12.0","homebridge":">=0.2.0"} (current: {"node":"0.10.42","npm":"1.4.21"})
npm ERR! not a package /tmp/npm-27239-M0SoFFBN/github.com/rudders/wemo-client.git
npm ERR! Error: ENOENT, open '/tmp/npm-27239-M0SoFFBN/github.com/rudders/wemo-client.git-unpack/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.8.13-bone70
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "homebridge-platform-wemo"
npm ERR! cwd /home/debian
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.4.21
npm ERR! path /tmp/npm-27239-M0SoFFBN/github.com/rudders/wemo-client.git-unpack/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/debian/npm-debug.log
npm ERR! not ok code 0
debian@beaglebone:~$

**Comment by rudders** [comment]
You have node version 0.10.42 installed and homebridge specifies 0.12.0 as a minimum and have you installed homebridge yet? it will have the same dependency so update node on you server then install hombridge and then the plugin.

**Comment by prich987** [comment]
Thanks for the help. I have attempted to update node and npm, but no luck. They don’t seem to find a newer version than what’s installed. I am a NOOB, so if you could let me know how to force it to grab newer versions that would be great.

Thanks,
Paul

ebian@beaglebone:~$ npm -v
1.4.21
debian@beaglebone:~$ node -v
v0.10.41
debian@beaglebone:~$ sudo npm install npm -g
\
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm@3.8.1 /usr/local/lib/node_modules/npm
debian@beaglebone:~$ 
debian@beaglebone:~$ npm -v
1.4.21
debian@beaglebone:~$ sudo npm install nodejs -g
/usr/lib
└── nodejs@0.0.0 

debian@beaglebone:~$ nodejs -v
v0.10.41
debian@beaglebone:~$ node -v
v0.10.41
debian@beaglebone:~$

**Comment by prich987** [comment]
I wound up upgrading the beaglebone to debian 8.3 from the 7.8 that I had been running and was able to get it to install and it appears to be working.

Thanks,
Paul
