### ISSUE TITLE
Setting a brightness on an individual light crashes homebridge

### ISSUE THREAD

**Issue by pewtertankard** [rudders/homebridge-platform-wemo#4]
In either of the two HomeKit UIs on my iPhone, the behaviour is a same: select an individual bulb (doesn't matter whether it's on or off) and slide the brightness to a value. Light comes on and brightness shifts to match... then the app says that all homebridge devices are unresponsive. When I check on the server, the service has stopped and needs to be restarted.

Only seems to happen on changing individual bulbs. If I set up a scene with bulbs at a different dimness, the scene change works and the service stays up OK.

**Comment by rudders** [comment]
can you send the log file that shows the error in homebridge please.

**Comment by pewtertankard** [comment]
Hope this helps. You can see the many attempts in the .log file as I drag the slider. The err file shows where it couldn't set the characteristic.

**Comment by pewtertankard** [comment]
Many thanks, Here’s the segment of homebridge.err showing the crash. I’ve obfuscated it to save sending real addresses etc. (I got a bit worried when I saw the WeMo real ids in the logs so I’ve stripped it of everything that could be used as a potential attack - if there’s a better way to obfuscate this then please let me know)

As you see, as I slide the dimmer bar along, the brightness values change until… well… bang.

Thanks again and for all your work on this.

Best wishes,

Phil

------

Fri, 18 Dec 2015 21:21:28 GMT Accessory [<homebridge-name>] Processing characteristic set: {"characteristics":[{"aid":8,"iid":10,"value":35}]}
Fri, 18 Dec 2015 21:21:28 GMT Accessory [<homebridge-name>] Setting Characteristic "Brightness" to value 35
Fri, 18 Dec 2015 21:21:28 GMT EventedHTTPServer [<ip-addr>6] Muting event '8.10' notification for this connection since it originated here.
Fri, 18 Dec 2015 21:21:28 GMT EventedHTTPServer [<ip-addr>6] HTTP Repsonse is finished
Fri, 18 Dec 2015 21:21:28 GMT EventedHTTPServer [<ip-addr>6] HTTP request: /characteristics
Fri, 18 Dec 2015 21:21:28 GMT HAPServer [<server-addr>] HAP Request: PUT /characteristics
Fri, 18 Dec 2015 21:21:28 GMT Accessory [<homebridge-name>] Processing characteristic set: {"characteristics":[{"aid":8,"iid":10,"value":34}]}
Fri, 18 Dec 2015 21:21:28 GMT Accessory [<homebridge-name>] Setting Characteristic "Brightness" to value 34
Fri, 18 Dec 2015 21:21:28 GMT EventedHTTPServer [<ip-addr>6] Muting event '8.10' notification for this connection since it originated here.
Fri, 18 Dec 2015 21:21:28 GMT EventedHTTPServer [<ip-addr>6] HTTP Repsonse is finished
Fri, 18 Dec 2015 21:21:28 GMT EventedHTTPServer [<ip-addr>6] HTTP request: /characteristics
Fri, 18 Dec 2015 21:21:28 GMT HAPServer [<server-addr>] HAP Request: PUT /characteristics
Fri, 18 Dec 2015 21:21:28 GMT Accessory [<homebridge-name>] Processing characteristic set: {"characteristics":[{"aid":8,"iid":10,"value":33}]}
Fri, 18 Dec 2015 21:21:28 GMT Accessory [<homebridge-name>] Setting Characteristic "Brightness" to value 33
Fri, 18 Dec 2015 21:21:28 GMT EventedHTTPServer [<ip-addr>6] Muting event '8.10' notification for this connection since it originated here.
Fri, 18 Dec 2015 21:21:28 GMT EventedHTTPServer [<ip-addr>6] HTTP Repsonse is finished
Fri, 18 Dec 2015 21:21:28 GMT EventedHTTPServer [<ip-addr>6] HTTP request: /characteristics
Fri, 18 Dec 2015 21:21:28 GMT HAPServer [<server-addr>] HAP Request: PUT /characteristics
Fri, 18 Dec 2015 21:21:28 GMT Accessory [<homebridge-name>] Processing characteristic set: {"characteristics":[{"aid":8,"iid":10,"value":32}]}
Fri, 18 Dec 2015 21:21:28 GMT Accessory [<homebridge-name>] Setting Characteristic "Brightness" to value 32
Fri, 18 Dec 2015 21:21:28 GMT EventedHTTPServer [<ip-addr>6] Muting event '8.10' notification for this connection since it originated here.
Fri, 18 Dec 2015 21:21:28 GMT EventedHTTPServer [<ip-addr>6] HTTP Repsonse is finished

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketOnEnd [as onend] (http.js:1568:23)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)

**Comment by rudders** [comment]
Doesn't give me too many clues I'm afraid - `socket hang up` could be a challenge to hunt down - could hang up because the module doesn't respond in time or maybe the memo switch. I'll have a new version of the module out in the next day or so that changes the architecture and will make calls much faster and may solve your problem - what OS are you running HomeBridge on btw? I've not seen this on OSX or Raspian.

**Comment by pewtertankard** [comment]
Am running this on Debian. However, that's Debian running inside a phpVirtualBox VM on my NAS. The NAS itself is based on FreeBSD hence can't run homebridge and hence the need for the Linux VM.

Many thanks for the suggestion. I will certainly give that a try.

**Comment by rudders** [comment]
Interesting setup - I'd be tempted to suggest that you should ensure you're on a version of node that is up to date on the version of Debian on you're NAS.

**Comment by pewtertankard** [comment]
Bang up to date. I used it as its my always-on machine without having to have another box (even one as small as a RPi) around. I also use that VM for CrashPlan so the VM has 3GB of RAM and the processor is an Intel Xeon (yeah, rather a beast of a NAS). It does run more slowly than native FreeBSD on the box but it should cope with me moving a slider bar :-)

I look forward to testing out the new build and letting you know. Thanks again

**Comment by pewtertankard** [comment]
Now fixed in 0.5.1 for me although I had to do a full reinstall of homebridge as your earlier message re node versions made me go and check things. The default"stable" version of node on Debian installed with apt-get install npm is 0.10. I now moved to node 0.12.9 and fully rebuilt everything.

Thanks for your help with this.

**Comment by pewtertankard** [comment]
Now fixed in 0.5.1 for me although I had to do a full reinstall of homebridge as your earlier message re node versions made me go and check things. The default"stable" version of node on Debian installed with apt-get install npm is 0.10. I now moved to node 0.12.9 and fully rebuilt everything.

Thanks for your help with this.

**Comment by rudders** [comment]
Sweet - glad it's working!

**Comment by kenderson** [comment]
I am seeing this issue on a fresh install of everything on a Raspberry PI. I followed these directions as part of the set-up - https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi

Every time I dim a light, it crashes homebridge with the following error;

```
[10/12/2016, 8:42:16 PM] [WeMo Platform] Ashleys Light - Set brightness: 50%
events.js:141
      throw er; // Unhandled 'error' event
      ^

ReferenceError: brightness is not defined
    at WemoLinkAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/index.js:940:37)
    at null.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:121:5)
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Object.onclosetag (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/node_modules/xml2js/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/node_modules/xml2js/node_modules/sax/lib/sax.js:645:5)
    at closeTag (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/node_modules/xml2js/node_modules/sax/lib/sax.js:905:7)
    at Object.write (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/node_modules/xml2js/node_modules/sax/lib/sax.js:1449:13)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/node_modules/xml2js/lib/xml2js.js:508:31)
    at Parser.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/node_modules/xml2js/lib/xml2js.js:7:59)
    at Object.exports.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/node_modules/xml2js/lib/xml2js.js:540:19)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:67:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
```

Is anybody else seeing this again?

Thanks All!

**Comment by devbobo** [comment]
@kenderson please check the `version` in the `package.json`, a fix for this issue was released in version `1.1.4`

**Comment by kenderson** [comment]
@devbobo Thanks for chiming in! Assume I'm a noob here - how do I get to the package.json file?

**Comment by devbobo** [comment]
@kenderson doing this might be easier...
`sudo npm install -g homebridge-platform-wemo@1.1.5`

**Comment by kenderson** [comment]
@devbobo That did the trick! Thank you for the recommendation!

**Comment by devbobo** [comment]
no probs, glad it's working now 👍
