### ISSUE TITLE
Add plugin-2 support

### ISSUE THREAD

**Issue by devbobo** [rudders/homebridge-platform-wemo#40]
Adding this as a bump to @rudders  ;)

The new `plugin-2` architecture on Homebridge 0.3.0+ provides a means to do lots of stuff that the plugin is currently trying to do...like device caching etc.

About a month ago, I rewrote the wemo plugin to support these new features. People are free to try my new version with the caveat that I haven't done any testing at all with WeMo Link bulbs. I've tried my best to ensure there won't be any issues, but I'm not sure if @rudders has got around to testing it.

**Please also note that using this version will recreate all your devices in HomeKit** as the new code uses the device's mac address or serial number to generate the HomeKit UUID instead of the device name as has been Homebridge's default method.

https://github.com/devbobo/homebridge-platform-wemo/tree/plugin-2

**Comment by rudders** [comment]
Sorry folks I have been busy and work and also overseas. Initial testing was all good but I lost a WEMO bulb so had t wait till I bought a replacement. Next few days I'll publish if I can. Maybe he Easter bunny will bring it.

**Comment by devbobo** [comment]
:+1:

**Comment by devbobo** [comment]
Done
