### ISSUE TITLE
Noobie One Kinobi - Help me with Homebridge/Wemo/Nest 

### ISSUE THREAD

**Issue by Johnnyk56791234** [rudders/homebridge-platform-wemo#41]
Hi
First of all , I'm quite new to all this so if anyone can help , speak to me like a four year old , it'll save time in the long run.

I have tried setting homebridge on both my Mac and a Pi, I still can't get beyond a certain point. I add Homebridge to Devices iOS app and it doesn't get any further. When I click on the homebridge icon - I just have grey square-Siri cannot find any devices !! I've seen on other videos that when you put in the pin and connect to the accessory eg Nest, the icon then turns into a thermostat icon. This doesn't happen for me. The I tried adding the Wemo plugin as I have 2 switches but it's the exact same result. I've been at this for weeks now so if anyone could shed some light on what I need to do I would greatly appreciate it...again if there is some info you may need could you give me the command that would get this info from Terminal on Mac OS Yosemite latest version is where I'm currently trying to get it going.

Again you could save my sanity by helping me :-(

Thanks on the off chance someone helps me !

Jk

**Comment by devbobo** [comment]
Is this still an issue ? Please reopen if required.

**Comment by Johnnyk56791234** [comment]
Still an issue !!

**Comment by devbobo** [comment]
Can you please share your config.json file ?
