### ISSUE TITLE
which plug-in's?

### ISSUE THREAD

**Issue by joe19812** [rudders/homebridge-platform-wemo#42]
Hello,
I'm new to github & npm.  Could  I please get  help to understand which plug-ins do I need to run wemo switches with home bridge?  There seems to be several, do I need them all:
homebridge
homebridge-wemo
wemo-client
homebridge-platform-wemo
others?
Thanks!
joe

**Comment by AppleTechy** [comment]
All you need to download is homebridge and homebridge-platform-Wemo.
(Homebridge-Wemo is outdated and is no longer being updated) And don't
forget to configure your homebridge config.json file

**Comment by rudders** [comment]
Thanks @AppleTechy

**Comment by joe19812** [comment]
Thank you sir!
