### ISSUE TITLE
Adding a type to a switch

### ISSUE THREAD

**Issue by pattyland** [rudders/homebridge-platform-wemo#46]
Hello there,

awesome plugin first of all. I have a hard time naming my switches because Siri is confused when I name things like device she know.

Example: I have a dishwasher behind an Insight switch. I named it "dishwasher". If I say "Turn dishwasher on" it works, but if I say "Turn **my** dishwasher on" Siri says that she can't find any dishwashers... like she is searching for devices but does not found one.

Can I configure that my wemo switch is discovered as a dishwasher?

Greets, Sören

**Comment by devbobo** [comment]
The new `1.0.0` release now adds the `Name` parameter for the Service, which should help in asking Siri to do thing. Please reopen if required.
