### ISSUE TITLE
WeMo Accessories not found - can we specify by IP?

### ISSUE THREAD

**Issue by DavidKep** [rudders/homebridge-platform-wemo#48]
Hi

Was using homebridge for awhile... after a wemo firmware update (which may be coincidental I don't know) no matter how many times I restart homebridge or how long I increase the wait time they are never found now.

I have a MacApp that controls them as well, and it also doesn't find them in a search, but if I enter the IP addresses for the two switches it works fine. Anyway to 'hardcode' the IPs of the WeMo's in homebridge-platform-wemo?

Any help appreciated...

`homebridge -D`
`*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.`
`*** WARNING *** Please fix your application to use the native API of Avahi!`
`*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>`
`*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only `
`supported partially) in the Apple Bonjour compatibility layer of Avahi.`
`*** WARNING *** Please fix your application to use the native API of Avahi!`
`*** WARNING *** For more information see <http://0pointer.de/avahi-compat?`
`s=libdns_sd&e=node&f=DNSServiceRegister>`
`[7/5/2016, 11:15:37 PM] Loaded plugin: homebridge-nest`
`[7/5/2016, 11:15:37 PM] Registering platform 'homebridge-nest.Nest'`
`[7/5/2016, 11:15:37 PM] ---`
`[7/5/2016, 11:15:37 PM] Loaded plugin: homebridge-platform-wemo`
`[7/5/2016, 11:15:37 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'`
`[7/5/2016, 11:15:37 PM] ---`
`[7/5/2016, 11:15:37 PM] Loaded config.json with 0 accessories and 2 platforms.`
`[7/5/2016, 11:15:37 PM] ---`
`[7/5/2016, 11:15:37 PM] Loading 2 platforms...`
`[7/5/2016, 11:15:37 PM] Initializing Nest platform...`
`[7/5/2016, 11:15:37 PM] Fetching Nest devices.`
`[7/5/2016, 11:15:37 PM] [WeMo Platform] Initializing BelkinWeMo platform...`
`[7/5/2016, 11:15:37 PM] [WeMo Platform] Wemo Platform Plugin Loaded `
`[7/5/2016, 11:15:37 PM] [WeMo Platform] Fetching the Wemo Accessories, expecting 2 and will wait 180 seconds to find them.`
`[7/5/2016, 11:15:44 PM] [NestFirebase] User null is logged in with custom`
`[7/5/2016, 11:15:44 PM] Software version for Dining Room Thermostat is: 5.5-5`
`[7/5/2016, 11:15:44 PM] Temperature unit for Dining Room Thermostat is: Fahrenheit`
`[7/5/2016, 11:15:44 PM] Current temperature for Dining Room Thermostat is: 72 F`
`[7/5/2016, 11:15:44 PM] Current humidity for Dining Room Thermostat is: 55%`
`[7/5/2016, 11:15:44 PM] Target temperature for Dining Room Thermostat is: 73 F`
`[7/5/2016, 11:15:44 PM] Target heating for Dining Room Thermostat is: Cooling`
`[7/5/2016, 11:15:44 PM] Away for Dining Room Thermostat is: 0`
`[7/5/2016, 11:15:44 PM] Initializing platform accessory 'Dining Room Thermostat'...`
`[7/5/2016, 11:18:37 PM] [WeMo Platform] We have timed out and only discovered 0 of the specified 2 devices - try restarting homebridge or increasing timeout in config.json`
`[7/5/2016, 11:18:37 PM] [WeMo Platform] and you have indicated you'd like to keep your HomeKit config safe so we're crashing out`
`/usr/lib/node_modules/homebridge-platform-wemo/index.js:110`
`                    throw new Error("homebridge-wemo-platform has intentially bought down HomeBridge - `
`please restart - sorry but it's your HomeKit configuration we're protecting!");`
`Error: homebridge-wemo-platform has intentially bought down HomeBridge - please restart - sorry but `
`it's your HomeKit configuration we're protecting!`
`    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-platform-wemo/index.js:110:27)`
`    at tryOnTimeout (timers.js:224:11)`
`    at Timer.listOnTimeout (timers.js:198:5)`

**Comment by devbobo** [comment]
@DavidKep I rewrote this plugin months ago to use new features of Homebridge which make all that code obsolete, but it's bit frustrating that it hasn't been merged into the main branch of the plugin.

Perhaps you can give this version of the plugin a go ?
https://github.com/rudders/homebridge-platform-wemo/tree/persist-homekit

Cheers,

David

**Comment by DavidKep** [comment]
@devbobo I think that worked! I was expecting to have to ask what changes in the config.json I needed but I just figured I'd run it first and it found both accessories.

Or I failed to install your branch correctly and this is all a total coincidence and everything just decided to work after a power outage reset everything but the centos server running home bridge.

I'm going to show you exactly what I did in case I didn't get your branch correctly. Honestly wasn't positive how to install from that branch and make sure I removed the previous version so I just executed:

`sudo npm uninstall homebridge-platform-wemo`
`sudo npm uninstall wemo-discover`
`cd .homebridge`
`git clone https://github.com/rudders/homebridge-platform-wemo.git`
`cd homebridge-platform-wemo`

here I just downloaded index.js and package.json with the text files on your branch on github

then:

`cd ..`
`sudo npm install ./homebridge-platform-wemo`
`homebridge -D`

And I get:

`[7/6/2016, 9:55:52 PM] Loaded plugin: homebridge-nest`
`[7/6/2016, 9:55:52 PM] Registering platform 'homebridge-nest.Nest'`
`[7/6/2016, 9:55:52 PM] ---`
`[7/6/2016, 9:55:52 PM] Loaded plugin: homebridge-platform-wemo`
`[7/6/2016, 9:55:52 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'`
`[7/6/2016, 9:55:52 PM] ---`
`[7/6/2016, 9:55:52 PM] Loaded config.json with 0 accessories and 2 platforms.`
`[7/6/2016, 9:55:52 PM] ---`
`[7/6/2016, 9:55:52 PM] Loading 2 platforms...`
`[7/6/2016, 9:55:52 PM] Initializing Nest platform...`
`[7/6/2016, 9:55:52 PM] Fetching Nest devices.`
`[7/6/2016, 9:55:52 PM] [WeMo Platform] Initializing BelkinWeMo platform...`
`[7/6/2016, 9:55:52 PM] [WeMo Platform] Wemo Platform Plugin Loaded `
`[7/6/2016, 9:55:52 PM] [WeMo Platform] Fetching the Wemo Accessories, expecting 2 and will wait 180 seconds to find them.`
`[7/6/2016, 9:55:52 PM] [WeMo Platform] Found: Behind TV, type: controllee`
`[7/6/2016, 9:55:52 PM] [WeMo Platform] Behind TV is false`
`[7/6/2016, 9:55:52 PM] [WeMo Platform] Discovered 1 accessories of 2 `
`[7/6/2016, 9:55:52 PM] [WeMo Platform] Found: Front Porch Light, type: lightswitch`
`[7/6/2016, 9:55:52 PM] [WeMo Platform] Front Porch Light is false`
`[7/6/2016, 9:55:52 PM] [WeMo Platform] Discovered 2 accessories of 2 `
`[7/6/2016, 9:55:52 PM] [WeMo Platform] Woohoo!!! all 2 accessories found.`
`[7/6/2016, 9:55:52 PM] [WeMo Platform] Initializing platform accessory 'Behind TV'...`
`[7/6/2016, 9:55:52 PM] [WeMo Platform] Initializing platform accessory 'Front Porch Light'...`
`[7/6/2016, 9:55:52 PM] [WeMo Platform] Behind TV binaryState: on`
`[7/6/2016, 9:55:52 PM] [WeMo Platform] Front Porch Light binaryState: on`

**Comment by devbobo** [comment]
@DavidKep no, I think that was just a coincidence.

after doing `git clone https://github.com/rudders/homebridge-platform-wemo.git`, you should do...
`cd homebridge-platform-wemo`
`sudo git checkout persist-homekit` -- this switches to the other branch

from there you can run `sudo npm install` to be safe, but everything should already be installed, then restart Homebridge.
