### ISSUE TITLE
Support for WeMo Light Switch

### ISSUE THREAD

**Issue by benmazin** [rudders/homebridge-platform-wemo#5]
Firstly thanks for your work on this homebridge plugin, I'm using it with the Insight Switch.
Do you have plans to support the WeMo Light Switch?

**Comment by rudders** [comment]
That's probably very easy I just need someone to test it for me - would you be willing to do that for me?

**Comment by benmazin** [comment]
Sure, let me know once you've made the changes.

**Comment by rudders** [comment]
Actually that should just work. Is it not being discovered or not working once discovered?

**Comment by benmazin** [comment]
homebridge finds the Light Switches, but they do not get Initialized

**Comment by rudders** [comment]
Could you change line 40 of index.js to the following and re-run it please and post the result when you restart - the wemo-client doesn't explicitly support them but I can't see why so lets just give it a go if you don't mind being a guinea pig
 
`self.log("Found: %s, type %s", device.friendlyName, device.deviceType);`

**Comment by rudders** [comment]
I've bumped to 0.5.2 so try and `npm -g update` and let me know how you go!

**Comment by benmazin** [comment]
verified the update works, the Light Switches were discovered and initialized straight away. Thanks making the changes so quickly!

**Comment by IMNotMax** [comment]
It works !
Insight and wall switches are initialized. I had to delete the previous homekit setup but now it's perfect !
Thanx @rudders for your great work !
