### ISSUE TITLE
homekit_safe - move to dynamic platform?

### ISSUE THREAD

**Issue by driskell** [rudders/homebridge-platform-wemo#52]
Hello!

Looking to use this soon and hoping I can provide some help enhancing :smile:

I've been playing with home bridge a while and the new dynamic platform system seems to work really really well. Is this something you've considered implementing? It would really help as it would remove the need for `homekit_safe` as accessories would not be forgotten.

Be good to know if this is something someone is already working on or if not, if it's something that would be interesting.

Thanks!

**Comment by driskell** [comment]
I can also see there's lots of code to handle loops where `set` triggers send to WeMo which triggers event and we call `set`. Way I handle this before is homebridge has a `context` parameter on the `setValue` calls which gets given to the `set` listener. If you pass, say, `_internal` as context, you can distinguish between `set` from Home and `set` from WeMo, removing all need to track current values. I can tackle this separately.

**Comment by driskell** [comment]
@rudders Hey just wondering if this is currently maintained as I can see not much has happened in a while? Appreciate you may be really busy. I'm just on the verge of starting the dynamic platform bit and would really like your thoughts before I head down any specific route as it would be great to be able to merge here for everyone else.

**Comment by thatskiff** [comment]
@driskell would the work you are planning here likely fix the issue raised at [github.com/rudders/homebridge-platform-wemo/issues/33](#33) ?

**Comment by masonjames** [comment]
@driskell I really appreciate your comments and PRs. I'm not affiliated with this repo, but use it at my place.  I switched to your repo today. _Finally_ I have my wemo devices interacting homebridge and am able to easily manage these devices along with many others.  Thanks for sharing!

**Comment by devbobo** [comment]
@driskell a dynamic platform already exists, I rewrote it earlier this year.

http://github.com/rudders/homebridge-platform-wemo/tree/persist-homekit?files=1

**Comment by devbobo** [comment]
I've merged my v2 code into `master`. @driskell I know you have also spent time writing your own v2 version of this plugin. I'd love to incorporate some of your changes particularly around the WemoLink devices. I'm more than happy to accept PRs.

**Comment by driskell** [comment]
@devbobo Great! If I find some time I will try raise some as it will be great to incorporate some bits.

Port allocation would be a good start (I contributed port specification to `wemo-client` and underlying `node-ssdp` to allow fixed ports - hopefully wemo-client released something). Also I can submit my changes around `_internal` parameter on `set` which avoids completely the need to compare-and-swap values, which significantly cleans up the code. Lastly I will then look at my transitioning code (which maybe less desirable but I like :smile:) - which delays events from the Wemo switches from toggling the state in Home App for a few seconds, so if you double tap something (e.g., whoops butter fingers hit wrong switch) - you don't get that flickering state due to the delays in Wemo switch telling it what state it is now in.
