### ISSUE TITLE
Changing brightness of Wemo bulbs causes Homebridge to crash

### ISSUE THREAD

**Issue by hauweit** [rudders/homebridge-platform-wemo#64]
@devbobo I've just updated to `homebridge-wemo-platform` version `1.1.3` and now changing brightness of bulbs cause Homebridge to crash. It traces back to line 940 of index.js where `brightness` isn't defined. 

I modified the line to `caller.brightness = value;` and brightness changes without crashing.

**Comment by devbobo** [comment]
`1.1.4` should resolve this, thanks @hauweit
