### ISSUE TITLE
No Motion Timer does not restart when motion detected

### ISSUE THREAD

**Issue by Siri4Eden** [rudders/homebridge-platform-wemo#65]
Using the default config.json settings:
1. - no motion timer started 60 secs
2. (if meanwhile motion detected it has no effect on the "no motion timer", does not restart "no motion timer")
3. after 60 secs - Motion Sensor: Clear, no motion timer completed

In other words the "no motion" is always triggered after 60 secs, even if there is motion during this period. I observe this behaviour in the last couple of releases (last 1-2 weeks), I am using 3 WeMo motion sensors.

Thanks for looking into this!

**Comment by devbobo** [comment]
@Siri4Eden thanks, should be fixed in `1.1.5`

**Comment by Siri4Eden** [comment]
@devbobo  Thank You for the quick fix! Works like a charm now!
