### ISSUE TITLE
Powering on/off one bulb seems to change the getStatus value of all of them

### ISSUE THREAD

**Issue by pewtertankard** [rudders/homebridge-platform-wemo#7]
Upgraded to 0.5.1 and now get a different (and far more critical) problem. I have two switches (Christmas tree and Paper Standard Lamp) and three bulbs at home. Bug is that when I start Homebridge afresh and change a bulb's power status from on to off, then Homebridge then suddenly reports all bulbs as being in that state (even though they're not). My Wemo app reports the correct state but Homebridge (and, by extension, all HomeKit apps) don't.

See the following example where changing one wall light (a bulb) to on and then off seems to also change the status of the Dining table light (another bulb) to false even though you can see earlier that this was set to on. I've only changed this via HomeKit and not Wemo.  To see the change via your iOS app of choice, you may have to leave the app and come back in (Eve for example will only show the problem after killing it and reloading it).

Homebridge is running on port 51827.
[WeMo Platform] getOnStatus: Dining table light is true
[WeMo Platform] getOn: Christmas tree is true
[WeMo Platform] getOn: Paper standard lamp is true
[WeMo Platform] getBrightness: Dining table light is 34
[WeMo Platform] getOnStatus: Wall light is false
[WeMo Platform] getBrightness: Wall light is 28
[WeMo Platform] getOnStatus: Porch light is false
[WeMo Platform] getOn: Christmas tree is true
[WeMo Platform] getBrightness: Porch light is 100
[WeMo Platform] getOn: Paper standard lamp is true
[WeMo Platform] getOnStatus: Dining table light is _*true*_
[WeMo Platform] getOnStatus: Wall light is false
[WeMo Platform] getOnStatus: Porch light is false
[WeMo Platform] getBrightness: Dining table light is 34
[WeMo Platform] getBrightness: Wall light is 28
[WeMo Platform] getBrightness: Porch light is 100
[WeMo Platform] getOnStatus: Wall light is false
[WeMo Platform] getOn: Christmas tree is true
[WeMo Platform] getOnStatus: Dining table light is true
[WeMo Platform] getBrightness: Wall light is 28
[WeMo Platform] getOn: Paper standard lamp is true
[WeMo Platform] getBrightness: Dining table light is 34
[WeMo Platform] setOnStatus: Wall light to 1
[WeMo Platform] statusChange: _{id for wall light}_ 10006 1
[WeMo Platform] statusChange: _{id for wall light}_ 10006 1
[WeMo Platform] statusChange: _{id for wall light}_ 10006 1
[WeMo Platform] setOnStatus: Wall light to 0
[WeMo Platform] statusChange: _{id for wall light}_ 10006 0
[WeMo Platform] statusChange: _{id for wall light}_ 10006 0
[WeMo Platform] statusChange: _{id for wall light}_ 10006 0
[WeMo Platform] getOn: Paper standard lamp is true
[WeMo Platform] getOn: Christmas tree is true
[WeMo Platform] getOnStatus: Porch light is false
[WeMo Platform] getOnStatus: Dining table light is _*false*_
[WeMo Platform] getOnStatus: Wall light is false
[WeMo Platform] getBrightness: Porch light is 100
[WeMo Platform] getBrightness: Dining table light is 34
[WeMo Platform] getBrightness: Wall light is 28

**Comment by rudders** [comment]
I have some real inconsistency with reporting the on/off state of Bulbs (via Wemo Link) is this problem just for Bulbs? I frequently see the on state as being reported incorrectly but the Wemo app gives the same inconsistency. I'll  look into it my end. Is it a consistent problem or intermittent?

**Comment by rudders** [comment]
There's been a lot of work on the plugin recently - please update and retest please.

**Comment by pewtertankard** [comment]
Sorry for the delay as I have been away (and hence checking the status of all my light bulbs is a hard problem). Have upgraded (_apt-get update_ and _apt-get upgrade_ followed by _npm upgrade -g_) to 0.5.5 and still have the problem. It is consistently giving the problem.

For a little more clarity, if I load one of my HomeKit enabled apps (Beam is a quick way to show this but Eve works just as well), and turn on or off an individual bulb, then the bulb status changes (both physically, emitting or ceasing to emit light, and in the getOnStatus) for that bulb. However, as soon as I quit the app and come back in again, this forces a refresh of all bulbs and they have now all changed to the status of that last bulb's status change (e.g. if I changed that one bulb to off, all bulbs on that WeMo Link now show as off).

It then gets worse if I go to a bulb which is showing as "off" when I can see that it's on. If I try to turn it on, nothing will happen. However, if I then go into my Wemo app (i.e. bypassing HomeKit) on my phone, I get a very curious error: Wemo can see three versions of each of my three bulbs _and_ it claims that it can't see the WeMo Link. If I kill the Homebridge service, remove and re-add the Wemo app on my phone, then all is OK (except that I can't use HomeKit of course).

Switches appear blissfully unaffected by all this and carry on working happily.

**Comment by pewtertankard** [comment]
Am happy to send more diagnostics but there's really nothing obvious in the logs regarding what's going on. I suspect it must be the interactions with the Wemo layer itself. Is there a flag I can set to enable a more detailed log trace?

**Comment by rudders** [comment]
I've played with this a bit today and am seeing similar issues. It starts a layer below my module so I've asked the maintainer of wemo-client if he's had any similar issues. Have a couple of ideas to try and sort it out - first option is a bit of a hack but might work while we dig into the wemo stack a bit.

**Comment by pewtertankard** [comment]
Many thanks for that and hope that progress can be made (am relieved that it's not just me anyway) as am really enjoying using your Wemo plugin.

**Comment by rudders** [comment]
I also have noticed that you clearly have multiple Wemo Links - which is a curve ball as I only have one to test with so there's a potential problem to research and I have also noted that the Wemo iOS app also reports brightness and on/off incorrectly intermittantly so there may be a platform issue - but should only effect the initial state after Homebridge starts, after that it should see all site changes. Working on it....

**Comment by rudders** [comment]
Could you restart Homebridge and give post the entire log - i.e the discovery and initialisation phase please. From about `Loaded plugin: homebridge-platform-wemo` onwards. Thanks.

**Comment by rudders** [comment]
@devbobo - have you seen this issue at all mate, and do you have multiple Wemo Links in your config?

**Comment by pewtertankard** [comment]
Hmmm... No I have only one Wemo link, although it is the second one that I've used (the first was from a starter kit that had a fault). Might see if I can perform a full Wemo reset to clear any "memory" of the old device.

Happy to send log file but is there a quick way to remove the unique Wemo ids (bit worried in case a reliable attack vector for Wemo rears its head)?

**Comment by devbobo** [comment]
@rudders, sorry I've only got Lifx globes

**Comment by pewtertankard** [comment]
Have done a full reset of both Wemo Links (I was about to send the old one back) and added back the first Wemo Link afresh, adding the three bulbs to that single bridge.

Here's the log of a fresh restart followed by me turning off the wall light and then re-grabbing the current on statuses (again, all the bulbs are now reporting off even though only the wall light was actually turned off... then I turned the wall light on and re-grabbed the on statuses... again, all bulbs now report on even though this isn't true.

Loaded plugin: homebridge-platform-wemo
Registering platform 'homebridge-platform-wemo.BelkinWeMo'
---
Loaded config.json with 0 accessories and 1 platforms.
---
Loading 1 platforms...
[WeMo Platform] Initializing BelkinWeMo platform...
[WeMo Platform] Wemo Platform Plugin Loaded 
[WeMo Platform] Fetching the Wemo Accessories, expecting an unknown number and will wait 10 seconds to find them.
[WeMo Platform] Found: Paper standard lamp, type: controllee
[WeMo Platform] Paper standard lamp is false
[WeMo Platform] Discovered 1 accessories of an unspecified number of accessories 
[WeMo Platform] Found: WeMo Link, type: bridge
[WeMo Platform] Found: Christmas tree, type: controllee
[WeMo Platform] Christmas tree is true
[WeMo Platform] Discovered 2 accessories of an unspecified number of accessories 
[WeMo Platform] Paper standard lamp binaryState: 1
[WeMo Platform] Christmas tree binaryState: 1
[WeMo Platform] Found endDevice: Dining table light, id: [id-of-Dining-table-light]
[WeMo Platform] Dining table light is true 1
[WeMo Platform] Dining table light is 34 bright
[WeMo Platform] Discovered 3 accessories of an unspecified number of accessories 
[WeMo Platform] Found endDevice: Wall light, id: [id-of-Wall-light]
[WeMo Platform] Wall light is true 1
[WeMo Platform] Wall light is 72 bright
[WeMo Platform] Discovered 4 accessories of an unspecified number of accessories 
[WeMo Platform] Found endDevice: Porch light, id: [id-of-Porch-light]
[WeMo Platform] Porch light is false 0
[WeMo Platform] Porch light is 100 bright
[WeMo Platform] Discovered 5 accessories of an unspecified number of accessories 
[WeMo Platform] Initializing platform accessory 'Paper standard lamp'...
[WeMo Platform] Initializing platform accessory 'Christmas tree'...
[WeMo Platform] Initializing platform accessory 'Dining table light'...
[WeMo Platform] Initializing platform accessory 'Wall light'...
[WeMo Platform] Initializing platform accessory 'Porch light'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
[30;47m                       [0m
[30;47m    ┌────────────┐     [0m
[30;47m    │ 031-45-154 │     [0m
[30;47m    └────────────┘     [0m
[30;47m                       [0m
Homebridge is running on port 51827.
[WeMo Platform] getOnStatus: Dining table light is true
[WeMo Platform] getBrightness: Dining table light is 34
[WeMo Platform] getOn: Christmas tree is true 
[WeMo Platform] getOnStatus: Wall light is true
[WeMo Platform] getOnStatus: Porch light is false
[WeMo Platform] getOn: Paper standard lamp is true 
[WeMo Platform] getBrightness: Wall light is 72
[WeMo Platform] getBrightness: Porch light is 100
[WeMo Platform] setOnStatus: Wall light to false
[WeMo Platform] getBrightness: Wall light is 72
[WeMo Platform] statusChange: [id-of-Wall-light] 10006 0
[WeMo Platform] statusChange: [id-of-Wall-light] 10006 0
[WeMo Platform] statusChange: [id-of-Wall-light] 10006 0
[WeMo Platform] getOn: Christmas tree is true 
[WeMo Platform] getOn: Paper standard lamp is true 
[WeMo Platform] getOnStatus: Porch light is false
[WeMo Platform] getOnStatus: Wall light is false
[WeMo Platform] getOnStatus: Dining table light is false
[WeMo Platform] getBrightness: Porch light is 100
[WeMo Platform] getBrightness: Wall light is 72
[WeMo Platform] getBrightness: Dining table light is 34
[WeMo Platform] setOnStatus: Wall light to true
[WeMo Platform] getBrightness: Wall light is 72
[WeMo Platform] statusChange: [id-of-Wall-light] 10006 1
[WeMo Platform] statusChange: [id-of-Wall-light] 10006 1
[WeMo Platform] statusChange: [id-of-Wall-light] 10006 1
[WeMo Platform] getOnStatus: Dining table light is true
[WeMo Platform] getBrightness: Dining table light is 34
[WeMo Platform] getOnStatus: Porch light is true
[WeMo Platform] getOnStatus: Wall light is true
[WeMo Platform] getOn: Christmas tree is true 
[WeMo Platform] getBrightness: Porch light is 100
[WeMo Platform] getBrightness: Wall light is 72
[WeMo Platform] getOn: Paper standard lamp is true

**Comment by rudders** [comment]
Thanks for this - I'm trying to work through a couple of issues and a downstream fix may help us here - I'll try and push a new version which will pull the newer wemo-client.

**Comment by rudders** [comment]
Try updating to 0.5.9 and see if the problem is resolved.

**Comment by pewtertankard** [comment]
Hmmm... Not sure the npm upgrade route is working. Your platform.json file seems to indicate 0.5.2 which is later than the 0.5.5 with which I'm currently operating. Am I missing something or should I manually swap out the JavaScript file? I'd prefer to upgrade via the supported route if possible.

**Comment by rudders** [comment]
`npm upgrade -g` should get you to 0.5.9. Might have to `npm upgrade -g` depending on your platform (which is what btw?)

**Comment by pewtertankard** [comment]
Nope sorry. _sudo npm upgrade -g_ is the first thing I tried.  As per previous discussions, running in a Debian VM within phpVirtualBox on a FreeNAS PC (i.e. a FreeBSD host).  Have previously used that call to upgrade with no problems. It's just now that it isn't working.

I tried specifically stating the package on that command line... still no joy.

Lastly, tried an uninstall and reinstall of homebridge-platform-wemo and voila... 0.5.9. If this happens in future I will do that.

Started 0.5.9 service and played about with bulbs' to turn them on and off.  Symptoms still remain. If I turn one bulb off, all of them appear to be off... etc.

**Comment by rudders** [comment]
Okay - thanks for persevering. I'm down to one wemo bulb currently due to a faulty unit so testing is a challenge. Now that I've got a couple of other things done I'll double down on your issue. You only have a single wemo link don't you?

**Comment by pewtertankard** [comment]
Many thanks and happy to keep persevering. Yes I've got one Wemo Link for my three bulbs.

**Comment by rudders** [comment]
could you possibly start home bridge with debug for wemo-client please and send me the output (will be a bit verbose).

`env DEBUG=wemo-client homebridge`

Thanks

**Comment by rudders** [comment]
I'm on the tail of this bug - should have a release out in the next few hours to resolve - thanks for your patience - assuming you don't have a voodoo doll of me with pins in it already......

**Comment by rudders** [comment]
homebridge-platform-wemo@0.6.2 should resolve this issue....

**Comment by pewtertankard** [comment]
Wonderful. That does indeed fix it (sorry for silence last 48 hours but I've not been home enough to get debug for you). Thanks for your help.

**Comment by rudders** [comment]
Excellent news! Thanks for letting me know!!
