### ISSUE TITLE
Logs from production homebridge instance being sent to DEBUG=* instance of homebridge

### ISSUE THREAD

**Issue by tmur11** [rudders/homebridge-platform-wemo#72]
I'm seeing my logs filled with wemo entries when running homebridge from a separate directory/config file with DEBUG=* and the `-U` parameter for my own development purposes of an unrelated plugin. 

Any thoughts why I'm seeing this? I wasn't before some of the latter updates. My full command is `DEBUG=* homebridge -U ~/.mydeveldirectory`

**Comment by devbobo** [comment]
Dynamic platform plugins are always loaded even if the plugin hasn't been added to the `config.json`

**Comment by devbobo** [comment]
homebridge-platform-wemo now exits if it doesn't have an entry in the `config.json` file.
