### ISSUE TITLE
Wemo Maker as Garage Door is not showing up in Automations

### ISSUE THREAD

**Issue by kenderson** [rudders/homebridge-platform-wemo#77]
First off - the work done in this plugin is awesome - thank you!

**My Goal:** Set-Up a homekit automation that will turn on the garage lights when the garage door is opened.

**Current Challenge:** When adding an automation via the Home App (selecting the "An accessory is controlled" option), the Garage Door (Maker) doesnt show up as a selectable accessory to start the automation. Only lights and switches show up.

I'm not sure if there's anything that can be done about this, but I thought I'd raise it up here in case there's a config/setting that can easily be adjusted.

Thanks Again!
Ken

**Comment by devbobo** [comment]
@kenderson, the `Home` app is still quite new and there is still loads of HomeKit stuff that isn't supported by the app. I'd suggest grabbing another app, like Eve for example. This allows you to set triggers based on door state..once you have configured the trigger go back to using the Home app.

![img_0233](https://cloud.githubusercontent.com/assets/680871/21475566/36ac4ce6-cb81-11e6-9b96-dc90e5085536.jpg)
