### ISSUE TITLE
Display Insight Switch as Outlet?

### ISSUE THREAD

**Issue by timothymills** [rudders/homebridge-platform-wemo#80]
In some of the promotional screens Apple uses on their [Homekit page](http://www.apple.com/ios/home/) you can see some outlets with an outlet icon. Is there a way to make the Insight Switch show up with this icon instead of as a switch?

**Comment by devbobo** [comment]
@timothymills this was a bit of a hangover from when the plugin was first written, it should be fixed in the next release

**Comment by timothymills** [comment]
Awesome. I tried to dig into the plugin to see where that was set, but my JavaScript skills are a little rusty/never that great to begin with.

**Comment by devbobo** [comment]
Version 1.1.7 should address this...but you will need to either reset Homebridge by deleting the `accessories` and `persist` folders or removing the individual devices using the Hesperus app.

**Comment by timothymills** [comment]
Thanks for this. I ended up deleting the `accessories` and `persist` folders. My Insight Switches are now showing up as outlets.
