### ISSUE TITLE
Wemo light switch keeps resetting to default room on reboot

### ISSUE THREAD

**Issue by rjmcfadd** [rudders/homebridge-platform-wemo#82]
I have a bunch of other accessories on homebridge but this Wemo switch is the only accessory that keeps resetting to default room when homebridge is restarted. Is there any fix for that?

**Comment by devbobo** [comment]
I've had these types of issues before if I had more than one `Home Hub` in HomeKit. How many do you have ?

Below is the way to find out...
1. Start `Home` app
2. Click `Location` icon as below...

     ![img_0142](https://cloud.githubusercontent.com/assets/680871/22851157/9100f49c-f06d-11e6-8b21-7808bbc647b8.jpg)
3. Select `Home Settings...`

     ![img_0143](https://cloud.githubusercontent.com/assets/680871/22851159/94067202-f06d-11e6-9d13-6262b9185e06.jpg)

4. Select the `Greater Than` icon on your Home... 

     ![img_0144](https://cloud.githubusercontent.com/assets/680871/22851213/de0cfe60-f06e-11e6-971e-0be4b756d461.jpg)

5. How many `Home Hubs` are listed ?

     ![img_0141](https://cloud.githubusercontent.com/assets/680871/22851160/96727662-f06d-11e6-9fee-12fa09768fc2.jpg)

**Comment by amitgandhinz** [comment]
I'm experiencing this issue also.  Every time i reboot homebridge.  I only have one Home, and this is the only accessory which reverts back to Default Room, and also gets removed from any scenes it was part of.  I wonder if theres an issue with how it uses the persists folder, or for some reason is generated as a new accessory each time?

**Comment by hjdhjd** [comment]
Same here.  Something's quirky. I have two WeMo light switches...one of them is always fine, and the other consistently gets reset to the default room. I only have one home, etc, etc.

**Comment by Kobosake** [comment]
Has anyone found a solution to this one? I have a single light bulb connected through my Wemo Link which is having this issue; all other bulbs connected to the Wemo Link are working fine.

**Comment by degofedal** [comment]
Thanks so much for this plugin. I'm having the same issue using a WEMO Maker with sensor as a Garage Door opener. Every time I reboot Homebridge it gets removed from all automations and associated scenes in the Home app. Really hoping for a solution. Thanks again.
