### ISSUE TITLE
Ignored devices example config

### ISSUE THREAD

**Issue by bvnovej** [rudders/homebridge-platform-wemo#86]
Hello I have been trying to ignore one of my Wemo devices but cannot seem to figure out how to do it.  I have tried adding serial number between the [ ] eg. "ignoredDevices": [221603S0000169].  But it doesn't seem to ignore the device when Homebridge is launched.  Is there any chance you can provide an example.
Thanks

**Comment by jngothia** [comment]
i have this question too!  I tried it with quotes around each serial number but the devices still seem to show up in the iOS home app.

**Comment by devbobo** [comment]
it should be like this...
```
"ignoredDevices": ["221603S0000169"]
```
```
"ignoredDevices": ["221603S0000169", "221603S0000170"]
```

**Comment by bvnovej** [comment]
Thank you worked first time!!!
