### ISSUE TITLE
Request: Allow manually configured ip

### ISSUE THREAD

**Issue by cnrd** [rudders/homebridge-platform-wemo#87]
Hi

First of all, thanks for all the awesome work you have been doing.

Problem: I have my WeMo switches on a dedicated VLAN for Internet of Things devices, which also means that the plugin is unable to discover any of my WeMo devices as they are on a different subnet.

I do however have the possibility to route packages to a from the WeMo swtiches using the IP of the WeMo switch. I am doing this in Home Assistant (Another controller software that I run for advanced automation) by allowing data to pass on port 49153 from Home Assistant to the WeMo switches and data on port 8989 from the WeMo switches to Home Assistant.

Solution: Allow manual config of IP of known WeMo devices.

Example of config (Just an idea):
 ```javascript
"platforms": [
    {
      "platform": "BelkinWeMo",
      "name": "WeMo Platform",
      "noMotionTimer": 60,
      "ignoredDevices": [],
      "manualDevices": ["1.2.3.4", "5.6.7.8", "4.3.2.1"]
    }   
]

```

I'm not really sure how hard it would be to implement, but it would be really great to be able to do this kind of config :-)

**Comment by djgreg13** [comment]
+1

**Comment by devbobo** [comment]
Version `1.2.0` now supports `manualDevices`. An array of device setup urls is expected in the form `http://{host}:{port}/setup.xml`.

There is also a new setting to disable `discovery` altogether, if not required.
```javascript
"platforms": [
   {
     "platform": "BelkinWeMo",
     "name": "WeMo Platform",
     "discovery": false,
     "manualDevices": ["http://192.168.1.20:49153/setup.xml"]
   }   
]
```
