### ISSUE TITLE
Any way to get wall switch consumption?

### ISSUE THREAD

**Issue by ooii** [rudders/homebridge-platform-wemo#88]
Hi,

I see in Homebridge logs the consumption updating every few seconds but it is not provided by the Home app. Is that normal?
Thanks.

**Comment by devbobo** [comment]
The official `Home` app is very new in comparison to `HomeKit`and has only really scratched the surface with functionality. I believe Apple will slowly roll out more functionality with each new iOS release.

In the meantime, you could try a 3rd party HomeKit app like `Eve` from Elgato.

**Comment by ooii** [comment]
Thanks for your answer.
