### ISSUE TITLE
Identifying switches as a different accessory?

### ISSUE THREAD

**Issue by CarterBrehm** [rudders/homebridge-platform-wemo#90]
Is there any way to simulate a certain other accessory instead of a switch? I ask because almost all of the WeMo light switches in my home are controlling light fixtures. I can set them (in the Home app) to be a light, but Siri still knows they're switches and controls them as such. (Ex: I can't say, "did I leave any lights on", I have to say, "did I leave any switches on").

What I'm asking for is a way to select certain switches and/or outlets by serial number or MAC, and setting their service type manually. Then, my lamp that is plugged into my WeMo outlet can be referred to as a light, rather than an outlet. I've tried to modify this plugin (with my meager skills) and I've had no success.

Please help!

**Comment by CarterBrehm** [comment]
#

**Comment by devbobo** [comment]
You can do this from the official Home app, no need to modify any code...

![img_0271](https://cloud.githubusercontent.com/assets/680871/25220304/bbb8894a-25f4-11e7-87a8-eae6479a805e.jpg)
![img_0272](https://cloud.githubusercontent.com/assets/680871/25220308/be5943e2-25f4-11e7-9358-dbe9555daa8e.jpg)
![img_0273](https://cloud.githubusercontent.com/assets/680871/25220313/c0d15a56-25f4-11e7-9fd8-89461f8eab63.jpg)
![img_0274](https://cloud.githubusercontent.com/assets/680871/25220316/c3ec2c5c-25f4-11e7-86d9-d42a5327b943.jpg)
![img_0275](https://cloud.githubusercontent.com/assets/680871/25220319/c55d9cec-25f4-11e7-9b47-02705ef30329.jpg)

**Comment by CarterBrehm** [comment]
Yes, but Siri recognizes it as an outlet, even after following these steps. You can choose the icon for the switch, but asking, "Did I leave any lights on?" doesn't work.
