### ISSUE TITLE
Insight switch no longer updating consumption info into terminal

### ISSUE THREAD

**Issue by macbisho** [rudders/homebridge-platform-wemo#91]
I swear that when I first set it up, the system reported every few moments with updates on consumption...

However, it no longer does. I've no idea how to troubleshoot this, so any suggestions would be great.

The insight switch is still reporting data to the Wemo app... so it's not the switch.

Any ideas?

`{
	"bridge": {
		"name": "TakeItToTheBridge",
		"username": "CC:22:3D:C3:CD:30",
		"port": 51826,
		"pin": "045-22-xxx"
	},
	"platforms": [{
	"platform": "BelkinWeMo",
	"name": "WeMo Platform",
	"noMotionTimer": 60,
	"ignoredDevices": []
}, {
	"platform": "Hue",
	"name": "Hue",
	"users": {
		"001788FFFEyyyyyy": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
		"001788FFFEyyyyyy": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"
	},
	"sensors": true,
	"excludeSensorTypes": ["Daylight", "CLIP", "Geofence"],
	"lights": true,
	"ct": true
}]
}`

**Comment by devbobo** [comment]
@macbisho Consumption info is updated via the plugin using udp broadcast messages, while I assume that the wemo app requests that info via a tcp request. I have seen this before with some of my devices...maybe try power cycling the insight and see if it starts broadcasting udp after it reboots.

**Comment by macbisho** [comment]
It's really weird - I've actually got Homebridge on two computers, two totally different instances (completely by accident). I've started up my first instance the other day and it is still seeing the updated energy consumption

[5/20/2017, 5:04:12 PM] [WeMo Platform] TV - Outlet In Use: Yes
[5/20/2017, 5:04:12 PM] [WeMo Platform] TV - Consumption: 43w
[5/20/2017, 5:04:12 PM] [WeMo Platform] TV - Total Consumption: 215.94kwh
[5/20/2017, 5:04:13 PM] [WeMo Platform] TV - Consumption: 45w
[5/20/2017, 5:04:15 PM] [WeMo Platform] TV - Consumption: 60w
[5/20/2017, 5:04:17 PM] [WeMo Platform] TV - Consumption: 63w
[5/20/2017, 5:04:19 PM] [WeMo Platform] TV - Consumption: 75w
[5/20/2017, 5:04:21 PM] [WeMo Platform] TV - Consumption: 91w
[5/20/2017, 5:04:23 PM] [WeMo Platform] TV - Consumption: 96w
[5/20/2017, 5:04:23 PM] [WeMo Platform] TV - Total Consumption: 216.5kwh
[5/20/2017, 5:04:25 PM] [WeMo Platform] TV - Consumption: 102w
[5/20/2017, 5:04:27 PM] [WeMo Platform] TV - Consumption: 103w

I've checked the config on this for homebridge-platform-wemo and it's nearly identical - it was done before I added the Hue devices, I'm assuming that the two plug-in's don't interfere.

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-XXX"
	},
	"accessories": [],

	"platforms": [{
		"platform": "BelkinWeMo",
		"name": "WeMo Platform",
		"expected_accessories": "4",
		"timeout": "60",
		"homekit_safe": "1"
	}]
}


I've changed my homebridge-platform-wemo to be similar to this, so it looks like this:

{
	"bridge": {
		"name": "HomeBridge",
		"username": "CC:22:3D:E3:EE:30",
		"port": 51826,
		"pin": "045-22-254"
	},
	"platforms": [{
	"platform": "BelkinWeMo",
	"name": "WeMo Platform",
	"expected_accessories": "5",
	"noMotionTimer": 60,
	"ignoredDevices": []
}, {
	"platform": "Hue",
	"name": "Hue",
	"users": {
		"001788FFFE2D2F78": "GQoEe0QV9c5EY2hF7q9QGZSSr-TwzJgdQDvwr3WJ",
		"001788FFFEyyyyyy": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"
	},
	"sensors": true,
	"excludeSensorTypes": ["Daylight", "CLIP", "Geofence"],
	"lights": true,
	"ct": true
}]
}

Any suggestions? Or what can I do if the consumption part is being force fed to my older Homebridge instance?

I've rebooted all the devices in my network - from Modem, router, wifi, each device and computer.

**Comment by macbisho** [comment]
Just to close this off, it's suddenly started to report data into HomeBridge.

Yay.
