### ISSUE TITLE
Issues with multiple network interfaces

### ISSUE THREAD

**Issue by joe248** [rudders/homebridge-platform-wemo#92]
See [this issue](https://github.com/timonreinhard/wemo-client/issues/49) I opened in wemo-client.

I'm running Homebridge on a CHIP. When I don't have my USB hub connected, everything works correctly and all of my Wemo devices are discovered. If I plug in my USB hub it adds additional network interfaces, one of which node-ssdp ends up binding to instead of the correct interface. This results in node-ssdp not being able to find any devices.

The latest node-ssdp (3.2.1) supports multiple network interfaces. By installing that and passing the option `explicitSocketBind: true` into the node-ssdp constructor, I was able to get things working again when my USB hub is connected.

Once the node-ssdp dependency is updated in wemo-client, we'll need to pass the `explicitSocketBind` option through wemo-client to node-ssdp like this:

`var wemo = new Wemo({discover_opts: {explicitSocketBind: true}});`

Or, we can make it a new config parameter in homebridge-platform-wemo.

**Comment by devbobo** [comment]
@joe248 waiting for a new release of `wemo-client`. I've made some changes to handle the new options.

I will be supporting it in the config file like this...

```
"platforms": [
    {
        "platform": "BelkinWemo",
        "name": "Belkin WeMo",
        "discover_opts": {explicitSocketBind: true}
    }
]
```

This will allow others to add other discovery options if required without any changes.

**Comment by devbobo** [comment]
@joe248 i've just release version `1.1.8`, you can pass in any initialisation options to `wemo-client` like below...

```javascript
"platforms": [
       {
           "platform": "BelkinWeMo",
           "name": "WeMo Platform",
           "wemoClient": {
               "port": 1234,
               "discover_opts": {
                   "unicastBindPort": 1235
               },
               "listen_interface": "wlan0"
           }
       }   
   ]
```

**Comment by joe248** [comment]
Thanks.  When I updated to your latest, it didn't pull the latest changes in wemo-client.  Is that because @timonreinhard hasn't bumped the package version, or do I need to do something special to get it to pull the latest wemo-client?

**Comment by timonreinhard** [comment]
There is no new release of `wemo-client`, yet. For early integration I suggest cloning the wemo-client repository and then using `npm link` as described here https://docs.npmjs.com/cli/link.

That said, I plan to release 0.12 – which will include @joe248's changes – latest tomorrow evening (UTC+2).

**Comment by joe248** [comment]
Sounds good.  Thank you both!

**Comment by devbobo** [comment]
@timonreinhard I realised that it wasn't released yet, but since I'm only passing through values to `wemo-client` I though releasing an updated module would allow @joe248 to test the new functionality as soon you release the new module

**Comment by timonreinhard** [comment]
wemo-client is now at 0.12.0 and includes @joe248's contribution.

**Comment by joe248** [comment]
Everything is working now.  Thanks!
