### ISSUE TITLE
Wemo Maker - Closed mode by default

### ISSUE THREAD

**Issue by ero589** [rudders/homebridge-platform-wemo#93]
Would like an option to set Wemo maker garage opener to "Closed" by default. Currently when Homebridge restarts it defaults to "Open"

**Comment by devbobo** [comment]
If you have a sensor wired into the Wemo Maker it works perfectly.

Using the Wemo Maker without a sensor as a Garage Door Opener isn't recommended. Given that homebridge has no clue as to what has happened to the state of the door between reboot, I don't really feel comfortable in setting the default state to `Closed`.

Spend the time to wire up a sensor.
