### ISSUE TITLE
WeMo Switch duration

### ISSUE THREAD

**Issue by rasgeek** [rudders/homebridge-platform-wemo#94]
Can i add duration on a demo switch, so i can just turn on an old kettle for say 2 mins and turn it back off ?

**Comment by devbobo** [comment]
Personally, I'd do this using a Rule in the WeMo app itself.

**Comment by macbisho** [comment]
Or you could do it using the Eve app, in rules - and that will flow into Home.app

**Comment by devbobo** [comment]
@macbisho except there is no built in way to do an off timer.

Given that the WeMo devices have a firmware functionality supporting that I believe it a better implemented there than moving it up to the HomeKit integration level.

**Comment by rasgeek** [comment]
Thanks Guys this is an awesome workaround

**Comment by rasgeek** [comment]
The wemo app only supports auto off duration of 1min, i modified a wemoswitch and added a external 5v relay to open my garage door, but i need the demo switch to turn off after 2 seconds in order to simulate a button press.
