### ISSUE TITLE
Wemo Dimmer Support (Enhancement Request)

### ISSUE THREAD

**Issue by ZubairAnwar** [rudders/homebridge-platform-wemo#99]
I am seeing a Not Supported error (urn:Belkin:device:dimmer:1) for the new Wemo Dimmer switch. Can support for this be added?

**Comment by devbobo** [comment]
@ZubairAnwar unfortunately, this device isn't currently available in Australia.

However, since Belkin have announced that a Wemo HomeKit Bridge will be available in Fall, ongoing development of this plugin probably won't be required.

**Comment by markhatchell** [comment]
I can provide the xml responses for all of the enpoints if that helps.

**Comment by markhatchell** [comment]
@ZubairAnwar Would you mind testing out a fork of this with basic dimmer support? The fork is at https://github.com/markhatchell/homebridge-platform-wemo you should be able to install it with 

`npm i https://github.com/markhatchell/homebridge-platform-wemo#master `

You will also need to override the wemo-client module with a fork of it at https://github.com/markhatchell/wemo-client

Again, an install can be run with

`npm i https://github.com/markhatchell/wemo-client#master`

**Comment by ZubairAnwar** [comment]
Unfortunately, I am currently out of town for the next three weeks. Would have been happy to test if I was not on the road...
________________________________________

**Comment by markhatchell** [comment]
After a weekend full of mDNS and SSDP multicast issues with my new network hardware I finally have everything working well again (no dropped home bridge connections from the AppleTV). The PR seems to work well for binary state (no, off) and I am working on the dimming functionality with great results using hap-nodejs and wemo-client for initial testing. I will bring dimming to the home bridge-platform-wemo module when all is perfect in a day or two.

**Comment by lucanaut** [comment]
This is great, thank you! I don't have the skills to help develop this but I did manage to successfully install homebridge and run it so I'm enjoying my wemo switches. I can't wait to be able to use the dimmers from HomeKit as well.
